/**
 * LIFE PATCH — Master Label Table (single source of truth)
 * ---------------------------------------------------------------
 * Row format:  key: { en: "English", hi: "हिन्दी", te: "తెలుగు" }
 *
 * • Add a new label  → add ONE row here (all languages in one place)
 * • Add a new locale → add a column per row + register it in
 *   SUPPORTED_LANGS (js/core/i18n.js) and the lang-select dropdowns
 * • Missing/empty language falls back to English at runtime
 * • Run `npm run i18n:check` to verify every data-i18n key in the
 *   HTML has all languages filled
 */
export const LABELS = {

  // ─── Core UI & Navigation ────────────────────────────────────────
  appName: { en: "LIFE PATCH", hi: "लाइफ पैच (LIFE PATCH)", te: "లైఫ్ ప్యాచ్ (LIFE PATCH)" },
  appTagline: { en: "Continuous Health Record for Rural & Public Healthcare", hi: "ग्रामीण और सार्वजनिक स्वास्थ्य के लिए निरंतर स्वास्थ्य रिकॉर्ड", te: "గ్రామీణ మరియు ప్రజా ఆరోగ్యం కోసం నిరంతర ఆరోగ్య రికార్డు" },
  demoMode: { en: "DEMO POC", hi: "डेमो मोड", te: "డెమో మోడ్" },
  connected: { en: "Connected to PHC", hi: "पीएचसी से जुड़ा हुआ है", te: "PHC కి అనుసంధానించబడింది" },
  offline: { en: "Offline Mode (Local Storage)", hi: "ऑफ़लाइन मोड (स्थानीय संग्रहण)", te: "ఆఫ్‌లైన్ మోడ్ (స్థానిక నిల్వ)" },
  login: { en: "Sign In", hi: "लॉग इन करें", te: "లాగిన్ చేయండి" },
  signInPersona: { en: "Sign In / Demo Access", hi: "डेमो लॉगिन / प्रोफाइल चुनें", te: "డెమో లాగిన్ / ప్రొఫైల్ ఎంచుకోండి" },
  navPortals: { en: "Portals", hi: "पोर्टल", te: "పోర్టల్స్" },
  navPipeline: { en: "Continuity Flow", hi: "स्वास्थ्य प्रवाह", te: "ఆరోగ్య ప్రవాహం" },
  navFeatures: { en: "Features", hi: "विशेषताएं", te: "ఫీచర్లు" },
  navMetrics: { en: "Specs & Performance", hi: "क्षमता और प्रदर्शन", te: "సామర్థ్యం & పనితీరు" },
  navJuryGuide: { en: "Jury Guide", hi: "मूल्यांकन गाइड", te: "జ్యూరీ గైడ్" },
  heroBadge: { en: "Smart India Hackathon 2026 • Problem Statement SIH26133", hi: "स्मार्ट इंडिया हैकाथॉन 2026 • समस्या SIH26133", te: "స్మార్ట్ ఇండియా హ్యాకథాన్ 2026 • సమస్య SIH26133" },
  heroTitle1: { en: "One Continuous Health Record.", hi: "एक निरंतर स्वास्थ्य रिकॉर्ड।", te: "ఒకే నిరంతర ఆరోగ్య రికార్డు." },
  heroTitle2: { en: "Every Village. Every Citizen.", hi: "हर गाँव। हर नागरिक।", te: "ప్రతి గ్రామం. ప్రతి పౌరుడు." },
  heroSubtitle: { en: "Bridging rural citizens, frontline ASHA workers, Primary Health Centres (PHCs), and specialist referral hospitals into an integrated, voice-enabled, consent-governed digital health ecosystem — with 100% offline-first resilience.", hi: "ग्रामीण नागरिकों, आशा कार्यकर्ताओं, प्राथमिक स्वास्थ्य केंद्रों (PHC) और विशेषज्ञ अस्पतालों को आवाज-सक्षम, सहमति-नियंत्रित डिजिटल स्वास्थ्य रिकॉर्ड से जोड़ना — शत-प्रतिशत ऑफ़लाइन क्षमता के साथ।", te: "గ్రామీణ పౌరులు, ఆశా కార్యకర్తలు, ప్రాథమిక ఆరోగ్య కేంద్రాలు (PHC) మరియు రిఫరల్ ఆసుపత్రులను వాయిస్-ఆధారిత, సమ్మతి-నియంత్రిత డిజిటల్ ఆరోగ్య రికార్డుతో అనుసంధానించడం — 100% ఆఫ్‌లైన్ సామర్థ్యంతో." },
  heroCtaLaunch: { en: "Launch Live Demo Portals", hi: "लाइव डेमो पोर्टल खोलें", te: "లైవ్ డెమో పోర్టల్స్ తెరవండి" },
  heroCtaPipeline: { en: "Explore Continuity Pipeline", hi: "स्वास्थ्य प्रवाह देखें", te: "ఆరోగ్య ప్రవాహాన్ని చూడండి" },
  trustIndexedDb: { en: "100% Client-Side IndexedDB", hi: "100% क्लाइंट-साइड IndexedDB", te: "100% క్లయింట్-సైడ్ IndexedDB" },
  trustAbdm: { en: "ABDM & ABHA Compliant", hi: "ABDM एवं ABHA अनुरूप", te: "ABDM మరియు ABHA అనుకూలమైనది" },
  trustVoiceAi: { en: "Multilingual Voice AI", hi: "बहुभाषी वॉयस एआई", te: "బహుభాషా వాయిస్ AI" },
  trustOffline: { en: "Zero-Connectivity Offline First", hi: "बिना इंटरनेट ऑफ़लाइन कार्य", te: "ఇంటర్నెట్ లేకపోయినా ఆఫ్‌లైన్ పనితీరు" },
  portalsHeading: { en: "Select an Interactive Workspace", hi: "एक इंटरैक्टिव पोर्टल चुनें", te: "ఇంటరాక్టివ్ వర్క్‌స్పేస్‌ను ఎంచుకోండి" },
  portalsSubheading: { en: "Explore tailored digital tools engineered for each stakeholder in the public healthcare continuum.", hi: "सार्वजनिक स्वास्थ्य प्रणाली के प्रत्येक हितधारक के लिए विशेष रूप से डिज़ाइन किए गए डिजिटल उपकरण।", te: "ప్రజారోగ్య వ్యవస్థలోని ప్రతి ఒక్కరి కోసం ప్రత్యేకంగా రూపొందించబడిన డిజిటల్ సాధనాలు." },
  patientBadge: { en: "Citizen Portal", hi: "नागरिक पोर्टल", te: "పౌరుల పోర్టల్" },
  patientWorkspaceTitle: { en: "Patient Portal", hi: "मरीज़ पोर्टल (Patient)", te: "రోగుల పోర్టల్ (Patient)" },
  patientWorkspaceDesc: { en: "Empowering rural citizens with voice-guided health logging, sovereign consent, and emergency assistance.", hi: "ग्रामीण नागरिकों को आवाज द्वारा लक्षण दर्ज करने, सहमति नियंत्रण और आपातकालीन सहायता प्रदान करता है।", te: "గ్రామీణ పౌరులకు వాయిస్ ద్వారా లక్షణాలు నమోదు చేసుకోవడం, గోప్యత నియంత్రణ మరియు అత్యవసర సహాయం అందిస్తుంది." },
  patientFeature1: { en: "Multilingual voice symptom recording (Hindi, Telugu, English)", hi: "हिंदी, तेलुगु और अंग्रेजी में आवाज द्वारा लक्षण रिकॉर्डिंग", te: "తెలుగు, హిందీ మరియు ఇంగ్లీష్‌లో వాయిస్ ద్వారా లక్షణాల నమోదు" },
  patientFeature2: { en: "Lifetime longitudinal medical timeline & prescriptions", hi: "आजीवन स्वास्थ्य टाइमलाइन और दवाइयों की पर्चियां", te: "జీవితకాల ఆరోగ్య కాలక్రమం మరియు మందుల చీటీలు" },
  patientFeature3: { en: "Digital ABHA Health Card with QR check-in", hi: "क्यूआर कोड सहित डिजिटल आभा (ABHA) स्वास्थ्य कार्ड", te: "QR కోడ్‌తో డిజిటల్ ఆభా (ABHA) హెల్త్ కార్డ్" },
  patientFeature4: { en: "108 Emergency SOS with live GPS telemetry", hi: "लाइव जीपीएस लोकेशन सहित 108 आपातकालीन एसओएस", te: "లైవ్ GPS లొకేషన్‌తో 108 అత్యవసర SOS సహాయం" },
  enterPatientBtn: { en: "Enter Patient Workspace", hi: "मरीज़ पोर्टल खोलें", te: "రోగుల పోర్టల్ తెరవండి" },
  doctorBadge: { en: "PHC Medical Officer", hi: "पीएचसी चिकित्सा अधिकारी", te: "PHC వైద్యాధికారి" },
  doctorWorkspaceTitle: { en: "Doctor Workspace", hi: "डॉक्टर वर्कस्पेस (Doctor)", te: "డాక్టర్ వర్క్‌స్పేస్ (Doctor)" },
  doctorWorkspaceDesc: { en: "Equipping PHC physicians with human-in-the-loop triage, AI summaries, and digital prescriptions.", hi: "चिकित्सकों को स्वचालित प्राथमिकता कतार, एआई सारांश और डिजिटल पर्चे प्रदान करता है।", te: "వైద్యులకు రోగుల ప్రాధాన్యతా క్యూ, AI సారాంశాలు మరియు డిజిటల్ ప్రిస్క్రిప్షన్‌లను అందిస్తుంది." },
  doctorFeature1: { en: "Automated OPD priority queue with doctor override", hi: "डॉक्टर नियंत्रण युक्त स्वचालित ओपीडी प्राथमिकता कतार", te: "డాక్టర్ నియంత్రణతో కూడిన ఆటోమేటెడ్ OPD ప్రాధాన్యతా క్యూ" },
  doctorFeature2: { en: "Grounded Clinical AI SOAP documentation assistant", hi: "सत्यापित क्लिनिकल एआई SOAP दस्तावेज़ सहायक", te: "ప్రామాణిక క్లినికల్ AI SOAP డాక్యుమెంటేషన్ అసిస్టెంట్" },
  doctorFeature3: { en: "e-Prescriptions with drug-allergy safety validation", hi: "दवा-एलर्जी सुरक्षा जांच युक्त ई-पर्चा (e-Rx)", te: "మందుల అలర్జీ భద్రతా తనిఖీతో e-ప్రిస్క్రిప్షన్" },
  doctorFeature4: { en: "District hospital cardiology & specialist referral routing", hi: "जिला अस्पताल कार्डियोलॉजी एवं विशेषज्ञ रेफरल", te: "జిల్లా ఆసుపత్రి కార్డియాలజీ & స్పెషలిస్ట్ రిఫరల్స్" },
  enterDoctorBtn: { en: "Enter Doctor Workspace", hi: "डॉक्टर वर्कस्पेस खोलें", te: "డాక్టర్ వర్క్‌స్పేస్ తెరవండి" },
  workerBadge: { en: "Frontline Health", hi: "आशा कार्यकर्ता", te: "ఆశా కార్యకర్త" },
  workerWorkspaceTitle: { en: "ASHA Health Worker", hi: "आशा कार्यकर्ता पोर्टल (ASHA)", te: "ఆశా కార్యకర్త పోర్టల్ (ASHA)" },
  workerWorkspaceDesc: { en: "Enabling frontline community health workers with offline field checkups and assisted access.", hi: "सामुदायिक स्वास्थ्य कार्यकर्ताओं को घर-घर जाकर ऑफ़लाइन जांच और नागरिक सहायता में सक्षम बनाता है।", te: "గ్రామీణ ఆరోగ్య కార్యకర్తలకు ఇంటి వద్దనే ఆఫ్‌లైన్ తనిఖీలు మరియు పౌర సహాయాన్ని అందిస్తుంది." },
  workerFeature1: { en: "Household field vitals entry (BP, Sugar, SpO2, Pulse)", hi: "घर-घर वाइटल्स माप (बीपी, शुगर, ऑक्सीजन SpO2, पल्स)", te: "ఇంటి వద్ద వైటల్స్ నమోదు (BP, షుగర్, ఆక్సిజన్ SpO2, పల్స్)" },
  workerFeature2: { en: "Assisted citizen login with verbal consent audit token", hi: "मौखिक सहमति ऑडिट टोकन सहित नागरिक सहायता लॉगिन", te: "మౌఖిక సమ్మతి ఆడిట్ టోకెన్‌తో సహాయక లాగిన్" },
  workerFeature3: { en: "Offline queue recording with 1-click background sync", hi: "1-क्लिक बैकग्राउंड सिंक युक्त ऑफ़लाइन डेटा कतार", te: "1-క్లిక్ బ్యాక్‌గ్రౌండ్ సింక్‌తో ఆఫ్‌లైన్ డేటా క్యూ" },
  workerFeature4: { en: "High-risk household monitoring & follow-up rosters", hi: "उच्च जोखिम वाले परिवारों की निगरानी एवं फॉलो-अप", te: "అధిక ప్రమాదం ఉన్న కుటుంబాల పర్యవేక్షణ" },
  enterWorkerBtn: { en: "Enter ASHA Workspace", hi: "आशा वर्कस्पेस खोलें", te: "ఆశా వర్క్‌స్పేస్ తెరవండి" },
  pipelineHeading: { en: "Continuity of Care Pipeline (SIH Architecture)", hi: "निरंतर स्वास्थ्य देखभाल प्रवाह (SIH आर्किटेक्चर)", te: "నిరంతర సంరక్షణ ప్రవాహం (SIH ఆర్కిటెక్చర్)" },
  pipelineSubheading: { en: "How medical intelligence flows seamlessly from rural doorstep to specialist tertiary hospitals without data fragmentation or loss of patient consent.", hi: "ग्रामीण घर से लेकर विशेषज्ञ अस्पताल तक बिना किसी डेटा हानि और पूर्ण सहमति के साथ स्वास्थ्य जानकारी का प्रवाह।", te: "గ్రామీణ ఇంటి నుండి స్పెషలిస్ట్ ఆసుపత్రి వరకు ఎలాంటి డేటా నష్టం లేకుండా సమాచార ప్రవాహం." },
  pipelineFhirTag: { en: "FHIR & ABDM Compliant Data Exchange", hi: "FHIR एवं ABDM अनुरूप डेटा साझाकरण", te: "FHIR & ABDM ప్రమాణాల డేటా మార్పిడి" },
  step1Title: { en: "1. Patient / Home", hi: "1. मरीज़ / घर", te: "1. రోగి / ఇల్లు" },
  step1Desc: { en: "Voice symptom entry in local dialect, instant 108 SOS trigger, and sovereign consent approvals.", hi: "स्थानीय भाषा में बोलकर लक्षण दर्ज करना, 108 एसओएस आपातकालीन संकेत और डेटा सहमति।", te: "స్థానిక భాషలో మాట్లాడి లక్షణాలు నమోదు చేయడం, 108 SOS మరియు డేటా సమ్మతి." },
  step1Tag: { en: "Speech-to-Text Input", hi: "स्पीच-टू-टेक्स्ट इनपुट", te: "స్పీచ్-టు-టెక్స్ట్ ఇన్‌పుట్" },
  step2Title: { en: "2. ASHA Field Visit", hi: "2. आशा कार्यकर्ता का दौरा", te: "2. ఆశా కార్యకర్త సందర్శన" },
  step2Desc: { en: "Offline vitals check (BP, SpO2, Sugar), paper slip OCR scan, and assisted verbal consent logging.", hi: "ऑफ़लाइन वाइटल्स जांच (बीपी, शुगर), पुरानी पर्ची ओसीआर स्कैन और मौखिक सहमति।", te: "ఆఫ్‌లైన్ వైటల్స్ తనిఖీ (BP, షుగర్), పాత చీటీల OCR స్కాన్ మరియు మౌఖిక సమ్మతి." },
  step2Tag: { en: "Offline IndexedDB Queue", hi: "ऑफ़लाइन IndexedDB कतार", te: "ఆఫ్‌లైన్ IndexedDB క్యూ" },
  step3Title: { en: "3. PHC Medical Officer", hi: "3. पीएचसी डॉक्टर", te: "3. PHC డాక్టర్" },
  step3Desc: { en: "Triage priority ranking, grounded AI SOAP clinical summary, electronic Rx, and e-consultation.", hi: "ओपीडी प्राथमिकता निर्धारण, क्लिनिकल एआई SOAP सारांश, डिजिटल पर्चा और परामर्श।", te: "ప్రాధాన్యత నిర్ధారణ, క్లినికల్ AI SOAP సారాంశం, డిజిటల్ చీటీ మరియు కన్సల్టేషన్." },
  step3Tag: { en: "Grounded Clinical AI", hi: "क्लिनिकल एआई सहायक", te: "క్లినికల్ AI అసిస్టెంట్" },
  step4Title: { en: "4. District Hospital", hi: "4. जिला अस्पताल", te: "4. జిల్లా ఆసుపత్రి" },
  step4Desc: { en: "Instant secondary referral intake with complete longitudinal historical EHR and zero data re-entry.", hi: "पूर्ण आजीवन स्वास्थ्य इतिहास के साथ विशेषज्ञ रेफरल और तुरंत उपचार।", te: "పూర్తి ఆరోగ్య రికార్డులతో స్పెషలిస్ట్ రిఫరల్ మరియు తక్షణ చికిత్స." },
  step4Tag: { en: "Longitudinal Referral", hi: "डिजिटल रेफरल ट्रांसफर", te: "డిజిటల్ రిఫరల్ బదిలీ" },
  metric1Val: { en: "< 35ms", hi: "< 35ms", te: "< 35ms" },
  metric1Label: { en: "Local Query Latency", hi: "लोकल डेटा स्पीड", te: "లోకల్ డేటా వేగం" },
  metric1Sub: { en: "Zero-server client-side indexed queries", hi: "बिना सर्वर के त्वरित क्लाइंट क्वेरी", te: "సర్వర్ అవసరం లేని శీఘ్ర క్లయింట్ క్వెరీలు" },
  metric2Val: { en: "17 Stores", hi: "17 स्टोर्स", te: "17 స్టోర్లు" },
  metric2Label: { en: "IndexedDB Schema", hi: "IndexedDB स्कीमा", te: "IndexedDB స్కీమా" },
  metric2Sub: { en: "Full offline persistence across refreshes", hi: "ब्राउज़र में पूर्ण ऑफ़लाइन डेटा सुरक्षा", te: "బ్రౌజర్‌లో పూర్తి ఆఫ్‌లైన్ డేటా భద్రత" },
  metric3Val: { en: "3 Dialects", hi: "3 भाषाएं", te: "3 భాషలు" },
  metric3Label: { en: "Speech-to-Text AI", hi: "वॉयस एआई समर्थन", te: "వాయిస్ AI మద్దతు" },
  metric3Sub: { en: "Native Hindi, Telugu, and English support", hi: "हिंदी, तेलुगु और अंग्रेजी में पूर्ण कार्य", te: "తెలుగు, హిందీ మరియు ఇంగ్లీష్‌లో పూర్తి పనితీరు" },
  metric4Val: { en: "100%", hi: "100%", te: "100%" },
  metric4Label: { en: "Offline Resilience", hi: "ऑफ़लाइन रेजिलिएंस", te: "ఆఫ్‌లైన్ రెసిలెన్స్" },
  metric4Sub: { en: "PWA Service Worker offline caching", hi: "पीडब्ल्यूए सर्विस वर्कर ऑफ़लाइन कैशिंग", te: "PWA సర్వీస్ వర్కర్ ఆఫ్‌లైన్ క్యాచింగ్" },
  pillarsHeading: { en: "Engineered for India's Public Healthcare Reality", hi: "भारत की ग्रामीण सार्वजनिक स्वास्थ्य आवश्यकताओं के अनुरूप निर्मित", te: "భారతీయ ప్రజా ఆరోగ్య అవసరాలకు అనుగుణంగా రూపొందించబడింది" },
  pillar1Title: { en: "Voice-First Accessibility", hi: "आवाज-प्रथम पहुंच (Voice AI)", te: "వాయిస్-ఫస్ట్ యాక్సెసిబిలిటీ (Voice AI)" },
  pillar1Desc: { en: "Overcomes rural literacy barriers through native speech recognition in regional Indian languages with automatic speech synthesis read-aloud.", hi: "क्षेत्रीय भारतीय भाषाओं में आवाज पहचान के माध्यम से ग्रामीण निरक्षरता की बाधा को दूर करता है।", te: "ప్రాంతీయ భారతీయ భాషలలో వాయిస్ రికగ్నిషన్ ద్వారా గ్రామీణ నిరక్షరాస్యత అడ్డంకులను అధిగమిస్తుంది." },
  pillar2Title: { en: "Offline-First IndexedDB", hi: "ऑफ़लाइन-प्रथम IndexedDB", te: "ఆఫ్‌లైన్-ఫస్ట్ IndexedDB" },
  pillar2Desc: { en: "Functions seamlessly in remote forest and rural tribal belts with zero mobile connectivity. Background synchronization pushes records when network returns.", hi: "इंटरनेट रहित सुदूर जंगलों और आदिवासी क्षेत्रों में भी बिना रुकावट काम करता है। नेटवर्क मिलने पर स्वतः सिंक होता है।", te: "ఇంటర్నెట్ లేని మారుమూల అటవీ మరియు గిరిజన ప్రాంతాల్లో కూడా నిరంతరాయంగా పనిచేస్తుంది." },
  pillar3Title: { en: "Grounded Clinical AI", hi: "क्लिनिकल एआई सहायक", te: "క్లినికల్ AI అసిస్టెంట్" },
  pillar3Desc: { en: "Human-in-the-loop medical AI summarizes complex longitudinal vitals and symptoms into structured SOAP notes without replacing licensed clinical judgment.", hi: "डॉक्टर के निर्णय में सहायता हेतु जटिल स्वास्थ्य डेटा को संरचित SOAP नोट्स में बदलता है।", te: "వైద్యుల నిర్ణయాలకు సహాయంగా సంక్లిష్ట ఆరోగ్య డేటాను నిర్మాణాత్మక SOAP నోట్స్‌గా మారుస్తుంది." },
  pillar4Title: { en: "ABDM & ABHA Integration", hi: "ABDM और आभा (ABHA) जुड़ाव", te: "ABDM మరియు ఆభా (ABHA) లింకేజ్" },
  pillar4Desc: { en: "Standardized 14-digit ABHA citizen identifier linkage with patient-controlled consent revocation for complete data sovereignty.", hi: "14-अंकीय आभा पहचान संख्या और मरीज़-नियंत्रित डेटा सहमति प्रबंधन।", te: "14-అంకెల ఆభా గుర్తింపు సంఖ్య మరియు రోగి-నియంత్రిత డేటా గోప్యతా నిర్వహణ." },
  pillar5Title: { en: "108 Emergency Telemetry", hi: "108 आपातकालीन टेलीमेट्री", te: "108 అత్యవసర టెలిమెట్రీ" },
  pillar5Desc: { en: "One-tap SOS broadcasts live GPS coordinates and critical allergy flags directly to emergency response ambulances and PHC dispatchers.", hi: "एक टैप से लाइव जीपीएस और एलर्जी संबंधी जानकारी सीधे 108 एम्बुलेंस और अस्पताल को प्रेषित।", te: "ఒకే ట్యాప్‌తో లైవ్ GPS మరియు అలర్జీ వివరాలు నేరుగా 108 అంబులెన్స్‌కు చేరుతాయి." },
  pillar6Title: { en: "Paper Record OCR Scan", hi: "कागज़ी पर्ची ओसीआर स्कैन", te: "పాత కాగితపు రికార్డుల OCR స్కాన్" },
  pillar6Desc: { en: "Transforms physical prescription slips and legacy hospital discharge cards into structured, queryable electronic health records.", hi: "पुरानी कागज़ी पर्चियों और अस्पताल कार्ड को डिजिटल स्वास्थ्य रिकॉर्ड में बदलता है।", te: "పాత కాగితపు ప్రిస్క్రిప్షన్‌లను డిజిటల్ ఆరోగ్య రికార్డులుగా మారుస్తుంది." },
  juryTourHeading: { en: "SIH Evaluator & Jury Quick-Start Tour", hi: "मूल्यांकनकर्ता एवं जूरी के लिए त्वरित टूर", te: "మూల్యాంకనం & జ్యూరీ కోసం త్వరిత గైడ్" },
  juryTourDesc: { en: "To test the complete cross-role feedback loop: Log a symptom in the Patient Voice Assistant → Observe priority queue elevation in the Doctor Workspace → Sign an e-prescription → Record household vitals in the ASHA Workspace → Sync offline queue.", hi: "संपूर्ण क्रॉस-रोल प्रवाह का परीक्षण करने के लिए: मरीज़ वॉयस असिस्टेंट में लक्षण बोलें → डॉक्टर वर्कस्पेस में कतार देखें → ई-पर्चा जारी करें → आशा वर्कस्पेस में वाइटल्स दर्ज करें → ऑफ़लाइन सिंक करें।", te: "మొత్తం ప్రక్రియను పరీక్షించడానికి: రోగుల వాయిస్ అసిస్టెంట్‌లో మాట్లాడండి → డాక్టర్ వద్ద క్యూ చూడండి → e-ప్రిస్క్రిప్షన్ ఇవ్వండి → ఆశా వర్క్‌స్పేస్‌లో వైటల్స్ నమోదు చేయండి → ఆఫ్‌లైన్ సింక్ చేయండి." },
  openRoleSwitcher: { en: "Open 1-Click Role Switcher", hi: "1-क्लिक रोल स्विचर खोलें", te: "1-క్లిక్ రోల్ స్విచర్ తెరవండి" },
  inspectDb: { en: "Inspect / Export IndexedDB", hi: "IndexedDB डेटा देखें / निर्यात करें", te: "IndexedDB డేటాను చూడండి / ఎగుమతి చేయండి" },
  readJuryDocs: { en: "Read Full Jury Documentation", hi: "पूर्ण जूरी दस्तावेज़ पढ़ें", te: "పూర్తి జ్యూరీ డాక్యుమెంటేషన్ చదవండి" },
  patient: { en: "Patient", hi: "मरीज़ (Patient)", te: "రోగి (Patient)" },
  doctor: { en: "Doctor", hi: "डॉक्टर (Doctor)", te: "వైద్యులు (Doctor)" },
  worker: { en: "ASHA Worker", hi: "आशा कार्यकर्ता (ASHA Worker)", te: "ఆశా కార్యకర్త (ASHA Worker)" },
  rolePatientDesc: { en: "Access health records, speak symptoms, view prescriptions and book visits.", hi: "स्वास्थ्य रिकॉर्ड देखें, लक्षण बोलकर बताएं, दवाएं देखें और अपॉइंटमेंट लें।", te: "ఆరోగ్య రికార్డులు చూడండి, మాట్లాడి లక్షణాలు చెప్పండి, మందుల వివరాలు మరియు అపాయింట్‌మెంట్లు." },
  roleDoctorDesc: { en: "Review patient queue, clinical records, prescribe medicines and issue referrals.", hi: "मरीज़ कतार देखें, नैदानिक रिकॉर्ड जांचें, दवा लिखें और रेफरल जारी करें।", te: "రోగుల క్యూ చూడండి, వైద్య రికార్డులు పరిశీలించండి, మందులు ప్రిస్క్రైబ్ చేయండి మరియు రిఫరల్స్ ఇవ్వండి." },
  roleWorkerDesc: { en: "Field vitals recording, assisted citizen access, and offline data sync.", hi: "फ़ील्ड वाइटल्स रिकॉर्डिंग, नागरिक सहायता और ऑफ़लाइन डेटा सिंक।", te: "ఫీల్డ్ వైటల్స్ నమోదు, పౌరుల సహాయం మరియు ఆఫ్‌లైన్ డేటా సింక్." },
  home: { en: "Home", hi: "होम", te: "హోమ్" },
  myHealth: { en: "My Health", hi: "मेरा स्वास्थ्य", te: "నా ఆరోగ్యం" },
  medicalRecords: { en: "Medical Records", hi: "स्वास्थ्य रिकॉर्ड", te: "వైద్య రికార్డులు" },
  symptoms: { en: "Symptoms", hi: "लक्षण (Symptoms)", te: "లక్షణాలు (Symptoms)" },
  voiceAssistant: { en: "Voice Assistant", hi: "आवाज सहायक (Voice)", te: "వాయిస్ అసిస్టెంట్ (Voice)" },
  appointments: { en: "Appointments", hi: "अपॉइंटमेंट", te: "అపాయింట్‌మెంట్లు" },
  emergency: { en: "Emergency SOS", hi: "आपातकालीन सहायता (SOS)", te: "అత్యవసర సహాయం (SOS)" },
  consentPrivacy: { en: "Consent & Privacy", hi: "सहमति और गोपनीयता", te: "సమ్మతి & గోప్యత (Consent)" },
  profile: { en: "Profile", hi: "प्रोफ़ाइल", te: "ప్రొఫైల్" },
  priorityQueue: { en: "Priority Queue", hi: "प्राथमिकता कतार (Queue)", te: "ప్రాధాన్యతా క్యూ (Queue)" },
  patients: { en: "Patients", hi: "मरीज़ सूची", te: "రోగుల జాబితా" },
  patientRecord: { en: "Patient Record", hi: "मरीज़ का रिकॉर्ड", te: "రోగి పూర్తి రికార్డు" },
  consultations: { en: "Consultations", hi: "परामर्श", te: "కన్సల్టేషన్లు" },
  prescriptions: { en: "Prescriptions", hi: "नुस्खा / दवाएं (Rx)", te: "మందుల చీటి (Prescriptions)" },
  referrals: { en: "Referrals", hi: "रेफरल (Referrals)", te: "రిఫరల్స్ (Referrals)" },
  followups: { en: "Follow-ups", hi: "फॉलो-अप", te: "ఫాలో-అప్‌లు" },
  assistedAccess: { en: "Assisted Access", hi: "सहायता प्राप्त लॉगिन", te: "సహాయక లాగిన్" },
  fieldVisit: { en: "Field Visit", hi: "घर का दौरा (Field Visit)", te: "ఇంటి సందర్శన (Field Visit)" },
  vitals: { en: "Vitals Entry", hi: "वाइटल्स माप", te: "వైటల్స్ కొలతలు" },
  voiceEntry: { en: "Voice Entry", hi: "आवाज़ प्रविष्टि", te: "వాయిస్ ఎంట్రీ" },
  offlineQueue: { en: "Offline Queue", hi: "ऑफ़लाइन कतार", te: "ఆఫ్‌లైన్ క్యూ" },
  sync: { en: "Sync Data", hi: "डेटा सिंक करें", te: "డేటా సింక్ చేయండి" },
  settings: { en: "Settings", hi: "सेटिंग्स", te: "సెట్టింగ్‌లు" },
  accessibility: { en: "Accessibility", hi: "पहुंच क्षमता (Accessibility)", te: "యాక్సెసిబిలిటీ (సౌలభ్యం)" },
  help: { en: "Help & Guide", hi: "मदद और गाइड", te: "సహాయం & గైడ్" },
  logout: { en: "Switch Role / Logout", hi: "लॉगआउट / भूमिका बदलें", te: "లాగౌట్ / పాత్ర మార్చండి" },
  backToDashboard: { en: "Back to Dashboard", hi: "डैशबोर्ड पर वापस जाएं", te: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి" },
  pageHelp: { en: "What can I do on this page?", hi: "इस पेज पर क्या कर सकते हैं?", te: "ఈ పేజీలో ఏమి చేయవచ్చు?" },
  pageHelpSubtitle: { en: "Quick guide for this screen", hi: "इस स्क्रीन की त्वरित गाइड", te: "ఈ స్క్రీన్ కోసం త్వరిత గైడ్" },
  fullGuide: { en: "Full User Guide", hi: "पूरी मदद गाइड", te: "పూర్తి యూజర్ గైడ్" },
  gotIt: { en: "Got It", hi: "समझ गया", te: "అర్థమైంది" },
  save: { en: "Save", hi: "सुरक्षित करें (Save)", te: "భద్రపరచు (Save)" },
  cancel: { en: "Cancel", hi: "रद्द करें (Cancel)", te: "రద్దు చేయి (Cancel)" },
  edit: { en: "Edit", hi: "बदलें (Edit)", te: "సవరించు (Edit)" },
  delete: { en: "Delete", hi: "हटाएं (Delete)", te: "తొలగించు (Delete)" },
  view: { en: "View", hi: "देखें (View)", te: "చూడండి (View)" },
  share: { en: "Share", hi: "साझा करें (Share)", te: "భాగస్వామ్యం (Share)" },
  bookVisit: { en: "Book PHC Visit", hi: "पीएचसी विजिट बुक करें", te: "PHC సందర్శన బుక్ చేయండి" },
  talkToDoctor: { en: "Talk to Doctor", hi: "डॉक्टर से बात करें", te: "డాక్టర్‌తో మాట్లాడండి" },
  tellHowYouFeel: { en: "Tell Us How You Feel", hi: "बताएं आप कैसा महसूस कर रहे हैं", te: "మీ ఆరోగ్యం ఎలా ఉందో చెప్పండి" },
  speak: { en: "Tap to Speak", hi: "बोलने के लिए दबाएं", te: "మాట్లాడటానికి నొక్కండి" },
  listening: { en: "Listening... Speak clearly", hi: "सुन रहे हैं... कृपया स्पष्ट बोलें", te: "వింటున్నాము... దయచేసి స్పష్టంగా మాట్లాడండి" },
  stopRecording: { en: "Stop Recording", hi: "रिकॉर्डिंग रोकें", te: "రికార్డింగ్ ఆపండి" },
  readAloud: { en: "Read Aloud", hi: "बोलकर सुनाएं", te: "వాయిస్ ద్వారా చదివి వినిపించండి" },
  exportData: { en: "Export Local Data", hi: "डेटा निर्यात करें (Export)", te: "డేటా ఎగుమతి చేయండి (Export)" },
  importData: { en: "Import Local Data", hi: "डेटा आयात करें (Import)", te: "డేటా దిగుమతి చేయండి (Import)" },
  resetDemoData: { en: "Reset Demo Data", hi: "डेमो डेटा रीसेट करें", te: "డెమో డేటా రీసెట్ చేయండి" },
  syncNow: { en: "Sync All Records", hi: "सभी रिकॉर्ड सिंक करें", te: "అన్ని రికార్డులను సింక్ చేయండి" },
  emergencyPri: { en: "Emergency", hi: "आपातकालीन (Emergency)", te: "అత్యవసరం (Emergency)" },
  highPri: { en: "High Priority", hi: "उच्च प्राथमिकता (High)", te: "అధిక ప్రాధాన్యత (High)" },
  mediumPri: { en: "Medium", hi: "मध्यम (Medium)", te: "మధ్యస్థం (Medium)" },
  routinePri: { en: "Routine", hi: "सामान्य (Routine)", te: "సాధారణం (Routine)" },
  unverified: { en: "Unverified (Patient Reported)", hi: "मरीज़ द्वारा सूचित (समीक्षा लंबित)", te: "రోగి తెలిపిన సమాచారం (సమీక్ష పెండింగ్)" },
  verified: { en: "Clinically Verified", hi: "डॉक्टर द्वारा सत्यापित", te: "డాక్టర్ ధృవీకరించినది" },
  active: { en: "Active", hi: "सक्रिय", te: "యాక్టివ్" },
  pending: { en: "Pending", hi: "लंबित", te: "పెండింగ్" },
  completed: { en: "Completed", hi: "पूर्ण", te: "పూర్తయింది" },
  goodMorning: { en: "Good morning", hi: "सुप्रभात", te: "శుభోదయం" },
  goodAfternoon: { en: "Good afternoon", hi: "शुभ दोपहर", te: "శుభ మధ్యాహ్నం" },
  goodEvening: { en: "Good evening", hi: "शुभ संध्या", te: "శుభ సాయంత్రం" },
  welcomeGreeting: { en: "Welcome", hi: "नमस्ते", te: "స్వాగతం" },
  healthAtAGlance: { en: "Your health at a glance", hi: "आपकी स्वास्थ्य स्थिति", te: "మీ ఆరోగ్య స్థితి సంగ్రహం" },
  nextAppointment: { en: "Next Appointment", hi: "अगली मुलाकात", te: "తదుపరి అపాయింట్‌మెంట్" },
  medicinesActive: { en: "Active Medicines", hi: "चल रही दवाएं", te: "ప్రస్తుత మందులు" },
  followUpDue: { en: "Follow-up Due", hi: "फॉलो-अप देय", te: "ఫాలో-అప్ సమయం" },
  recentTimeline: { en: "Recent Health Timeline", hi: "हालिया स्वास्थ्य टाइमलाइन", te: "ఇటీవలి ఆరోగ్య కాలక్రమం" },
  noRecordsYet: { en: "No medical records found yet.", hi: "अभी कोई रिकॉर्ड नहीं है।", te: "ఇంకా ఎలాంటి రికార్డులు నమోదు కాలేదు." },
  voiceInstruction: { en: "Press the microphone and describe your symptoms in your own words.", hi: "माइक दबाएं और अपनी भाषा में बताएं कि आपको क्या तकलीफ़ है।", te: "మైక్ బటన్ నొక్కి మీ లక్షణాలను మీ సొంత మాటల్లో చెప్పండి." },
  weHeard: { en: "We heard:", hi: "हमने यह सुना:", te: "మేము విన్నది:" },
  confirmAndSave: { en: "Save to Health Record", hi: "स्वास्थ्य रिकॉर्ड में जोड़ें", te: "ఆరోగ్య రికార్డులో భద్రపరచు" },
  reportSymptomsTitle: { en: "Report Symptoms", hi: "लक्षण दर्ज करें", te: "లక్షణాలు నమోదు చేయండి" },
  reportSymptomsDesc: { en: "Speak or type your symptoms — they go straight to your PHC doctor and ASHA worker for review.", hi: "अपने लक्षण बोलें या टाइप करें — ये सीधे आपके PHC डॉक्टर और आशा कार्यकर्ता के पास समीक्षा के लिए जाते हैं।", te: "మీ లక్షణాలను మాట్లాడండి లేదా టైప్ చేయండి — అవి నేరుగా మీ PHC డాక్టర్ మరియు ఆశా కార్యకర్తకు సమీక్ష కోసం వెళ్తాయి." },
  voiceCaptureTitle: { en: "Describe by Voice", hi: "बोलकर बताएं", te: "మాట్లాడి చెప్పండి" },
  selectSpeechLang: { en: "Spoken Language:", hi: "बोलने की भाषा:", te: "మాట్లాడే భాష:" },
  tapMicToSpeak: { en: "Tap the microphone to speak", hi: "बोलने के लिए माइक्रोफ़ोन दबाएं", te: "మాట్లాడటానికి మైక్రోఫోన్ నొక్కండి" },
  listeningNow: { en: "Listening… speak now", hi: "सुन रहे हैं… अब बोलें", te: "వింటున్నాం… ఇప్పుడు మాట్లాడండి" },
  voiceTranscriptPh: { en: "Your spoken words appear here — or type directly...", hi: "आपके बोले शब्द यहां दिखेंगे — या सीधे टाइप करें...", te: "మీరు మాట్లాడిన మాటలు ఇక్కడ కనిపిస్తాయి — లేదా నేరుగా టైప్ చేయండి..." },
  clearText: { en: "Clear", hi: "साफ़ करें", te: "క్లియర్ చేయండి" },
  useThisText: { en: "Use this text", hi: "यह टेक्स्ट इस्तेमाल करें", te: "ఈ టెక్స్ట్ ఉపయోగించండి" },
  micNoticeTitle: { en: "Microphone Access Notice", hi: "माइक्रोफ़ोन सूचना", te: "మైక్రోఫోన్ నోటీసు" },
  micNoticeText: { en: "Allow microphone access, use a sample phrase, or type your symptom below.", hi: "माइक्रोफ़ोन की अनुमति दें, कोई सैंपल वाक्य चुनें, या नीचे लक्षण टाइप करें।", te: "మైక్రోఫోన్ అనుమతి ఇవ్వండి, నమూనా వాక్యం ఉపయోగించండి, లేదా క్రింద టైప్ చేయండి." },
  micErrBlocked: { en: "Microphone is blocked — please allow mic access, or use a sample phrase / type below.", hi: "माइक्रोफ़ोन ब्लॉक है — कृपया माइक की अनुमति दें, या नमूना वाक्य चुनें / नीचे टाइप करें।", te: "మైక్రోఫోన్ బ్లాక్ చేయబడింది — దయచేసి మైక్ యాక్సెస్ అనుమతించండి, లేదా నమూనా వాక్యం / క్రింద టైప్ చేయండి." },
  micErrUnsupported: { en: "Voice input is not supported in this browser — please type your symptom instead.", hi: "इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है — कृपया अपना लक्षण टाइप करें।", te: "ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ సపోర్ట్ లేదు — దయచేసి మీ లక్షణాన్ని టైప్ చేయండి." },
  micErrNetwork: { en: "Voice recognition for this language needs an internet connection and isn't responding right now — retry, or type / use a sample phrase below.", hi: "इस भाषा के लिए वॉयस पहचान सेवा को इंटरनेट चाहिए और अभी जवाब नहीं दे रही — पुनः प्रयास करें, या नीचे टाइप करें / नमूना वाक्य चुनें।", te: "ఈ భాషకు వాయిస్ గుర్తింపుకు ఇంటర్నెట్ కావాలి మరియు ప్రస్తుతం స్పందించడం లేదు — మళ్ళీ ప్రయత్నించండి, లేదా క్రింద టైప్ చేయండి / నమూనా వాక్యం వాడండి." },

  micErrGeneric: { en: "Voice input had a problem — you can still type in the fields below.", hi: "वॉयस इनपुट में समस्या आई — आप नीचे फ़ील्ड में टाइप कर सकते हैं।", te: "వాయిస్ ఇన్‌పుట్‌లో సమస్య వచ్చింది — మీరు క్రింది ఫీల్డ్‌లలో టైప్ చేయవచ్చు." },
  symptomDetailsTitle: { en: "Symptom Details", hi: "लक्षण का विवरण", te: "లక్షణ వివరాలు" },
  symptomNameLabel: { en: "What are you experiencing?", hi: "आपको क्या तकलीफ़ है?", te: "మీకు ఏ ఇబ్బంది ఉంది?" },
  symptomNamePh: { en: "e.g. Dizziness, headache, shortness of breath", hi: "जैसे: चक्कर, सिरदर्द, सांस लेने में तकलीफ़", te: "ఉదా: తల తిరుగుట, తలనొప్పి, శ్వాస ఇబ్బంది" },
  whenStartLabel: { en: "When did it start?", hi: "यह कब शुरू हुआ?", te: "ఇది ఎప్పుడు మొదలైంది?" },
  severityLabel: { en: "How severe is it?", hi: "यह कितना गंभीर है?", te: "ఇది ఎంత తీవ్రంగా ఉంది?" },
  sevMild: { en: "Mild (noticeable, routine continues)", hi: "हल्का (दिखता है, दिनचर्या चलती है)", te: "తక్కువ (గమనించదగినది, పనులు జరుగుతాయి)" },
  sevModerate: { en: "Moderate (disrupts normal activity)", hi: "मध्यम (सामान्य काम में बाधा)", te: "మధ్యస్థం (సాధారణ పనులకు అడ్డంకి)" },
  sevSevere: { en: "Severe (urgent / unbearable)", hi: "गंभीर (तुरंत / असहनीय)", te: "తీవ్రం (అత్యవసరం / భరించలేనిది)" },
  addDetailsLabel: { en: "Additional details (optional)", hi: "अतिरिक्त विवरण (वैकल्पिक)", te: "అదనపు వివరాలు (ఐచ్ఛికం)" },
  addDetailsPh: { en: "e.g. Occurs mostly in the morning, with mild blurred vision...", hi: "जैसे: ज़्यादातर सुबह होता है, हल्की धुंधली नज़र...", te: "ఉదా: ఎక్కువగా ఉదయం జరుగుతుంది, కంటి చూపు మసక..." },
  saveSymptomBtn: { en: "Save Symptom Report", hi: "लक्षण रिपोर्ट सहेजें", te: "లక్షణ నివేదిక సేవ్ చేయండి" },
  aiAssistantTitle: { en: "Clinical AI Assistant (Demo)", hi: "क्लिनिकल एआई सहायक (डेमो)", te: "క్లినికల్ AI అసిస్టెంట్ (డెమో)" },
  aiDisclaimerNotice: { en: "AI-assisted summarisation for clinician review. Final medical decisions remain with the doctor.", hi: "डॉक्टर की सहायता के लिए सारांश। अंतिम चिकित्सा निर्णय केवल डॉक्टर द्वारा लिया जाता है।", te: "డాక్టర్ సమీక్ష కోసం మాత్రమే రూపొందించబడిన సారాంశం. అంతిమ వైద్య నిర్ణయం డాక్టర్‌దే." },
  generateSummary: { en: "Generate Clinical Summary", hi: "क्लिनिकल सारांश बनाएं", te: "క్లినికల్ సారాంశం తయారుచేయి" },
  emergencyHeader: { en: "EMERGENCY MEDICAL ASSISTANCE", hi: "आपातकालीन चिकित्सा सहायता", te: "అత్యవసర వైద్య సహాయం" },
  emergencyPrompt: { en: "If you are experiencing severe chest pain, breathing difficulty, or trauma, press the button below.", hi: "यदि आपको सीने में तेज़ दर्द, सांस लेने में तकलीफ़ या गंभीर चोट है, तो नीचे का बटन दबाएं।", te: "మీకు తీవ్రమైన గుండెనొప్పి, శ్వాస తీసుకోవడంలో ఇబ్బంది లేదా గాయాలు ఉంటే వెంటనే క్రింది బటన్ నొక్కండి." },
  callEmergency: { en: "🚨 REQUEST EMERGENCY HELP", hi: "🚨 आपातकालीन सहायता मांगें", te: "🚨 అత్యవసర సహాయం కోరండి" },
  simulatedNotice: { en: "DEMO MODE — This screen simulates emergency dispatch. No actual ambulance is dispatched.", hi: "डेमो मोड — यह स्क्रीन आपातकालीन प्रक्रिया दर्शाती है। कोई वास्तविक एम्बुलेंस नहीं भेजी जाती।", te: "డెమో మోడ్ — ఇది అత్యవసర ప్రక్రియను ప్రదర్శించడానికి మాత్రమే. నిజమైన అంబులెన్స్ పంపబడదు." },

  // ─── Patient Portal ──────────────────────────────────────────────
  emergencySOS: { en: "Emergency 108 SOS", hi: "आपातकालीन 108 SOS", te: "అత్యవసర 108 SOS" },
  patDashBpLabel: { en: "Blood Pressure", hi: "ब्लड प्रेशर (BP)", te: "బ్లడ్ ప్రెషర్ (BP)" },
  patDashSugarLabel: { en: "Random Sugar", hi: "रैंडम शुगर (Sugar)", te: "ర్యాండమ్ షుగర్ (Sugar)" },
  patDashBgLabel: { en: "Blood Group", hi: "ब्लड ग्रुप", te: "బ్లడ్ గ్రూప్" },
  patDashMedsList: { en: "Metformin (BD), Amlodipine (OD)", hi: "मेटफॉर्मिन (BD), एम्लोडिपाइन (OD)", te: "మెట్‌ఫార్మిన్ (BD), అమ్‌లోడిపైన్ (OD)" },
  patDashReferrals: { en: "Hospital Referrals", hi: "अस्पताल रेफरल", te: "ఆసుపత్రి రిఫరల్స్" },
  patDashReferralSub: { en: "District Hospital (Cardiology)", hi: "जिला अस्पताल (कार्डियोलॉजी)", te: "జిల్లా ఆసుపత్రి (కార్డియాలజీ)" },
  patDashAbdmTitle: { en: "AYUSHMAN BHARAT DIGITAL MISSION", hi: "आयुष्मान भारत डिजिटल मिशन", te: "ఆయుష్మాన్ భారత్ డిజిటల్ మిషన్" },
  patDashAbhaLinked: { en: "ABHA LINKED", hi: "ABHA जुड़ा हुआ", te: "ABHA లింక్ చేయబడింది" },
  patDashAbhaNumber: { en: "ABHA Number", hi: "आभा (ABHA) नंबर", te: "ఆభా (ABHA) నంబర్" },
  patDashAbhaMeta: { en: "DOB: 1974 • Female • Health ID: LP-10234", hi: "जन्म: 1974 • महिला • हेल्थ ID: LP-10234", te: "పుట్టిన సంవత్సరం: 1974 • స్త్రీ • హెల్త్ ID: LP-10234" },
  patDashCopyBtn: { en: "Copy", hi: "कॉपी करें", te: "కాపీ చేయండి" },
  patDashVitalsTitle: { en: "My Vitals History", hi: "मेरे वाइटल्स का इतिहास", te: "నా వైటల్స్ చరిత్ర" },
  patDashAshaSync: { en: "ASHA Sync", hi: "आशा सिंक (ASHA Sync)", te: "ఆశా సింక్ (ASHA Sync)" },
  patDashQuickServices: { en: "Quick Healthcare Services", hi: "त्वरित स्वास्थ्य सेवाएं", te: "త్వరిత ఆరోగ్య సేవలు" },
  patDashVoiceDesc: { en: "Speak in Hindi, Telugu, or English to record your health symptoms", hi: "अपने लक्षण दर्ज करने के लिए हिंदी, तेलुगु या अंग्रेजी में बोलें", te: "మీ లక్షణాలను నమోదు చేయడానికి తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో మాట్లాడండి" },
  patDashRecordsDesc: { en: "View your complete health timeline, prescription slips & doctor notes", hi: "अपना पूरा स्वास्थ्य इतिहास, पर्चे और डॉक्टर के नोट्स देखें", te: "మీ పూర్తి ఆరోగ్య కాలక్రమం, ప్రిస్క్రిప్షన్ చీటీలు & డాక్టర్ నోట్స్ చూడండి" },
  patDashAptDesc: { en: "Schedule a clinic visit and reserve your instant OPD token", hi: "क्लीनिक विजिट तय करें और तुरंत OPD टोकन पाएं", te: "క్లినిక్ సందర్శన షెడ్యూల్ చేసి, మీ OPD టోకెన్ వెంటనే పొందండి" },
  patDashSosDesc: { en: "One-tap emergency ambulance dispatch with live GPS location share", hi: "एक टैप से लाइव GPS लोकेशन के साथ एम्बुलेंस बुलाएं", te: "ఒకే ట్యాప్‌తో లైవ్ GPS లొకేషన్‌తో అంబులెన్స్ పిలవండి" },
  patDashRecentEvents: { en: "Recent Health Events", hi: "हालिया स्वास्थ्य घटनाएं", te: "ఇటీవలి ఆరోగ్య సంఘటనలు" },
  patDashViewAll: { en: "View All Records", hi: "सभी रिकॉर्ड देखें", te: "అన్ని రికార్డులు చూడండి" },
  recordsDesc: { en: "Unified lifetime health history across PHCs, private clinics, and district hospitals.", hi: "पीएचसी, निजी क्लीनिक और जिला अस्पतालों का एकीकृत आजीवन स्वास्थ्य इतिहास।", te: "PHCలు, ప్రైవేట్ క్లినిక్‌లు మరియు జిల్లా ఆసుపత్రుల అంతటా ఏకీకృత జీవితకాల ఆరోగ్య చరిత్ర." },
  recordsPrintBtn: { en: "Print Timeline", hi: "टाइमलाइन प्रिंट करें", te: "టైమ్‌లైన్ ప్రింట్ చేయండి" },
  recordsOcrBtn: { en: "Digitise Paper Record (OCR)", hi: "कागज़ी रिकॉर्ड डिजिटल करें (OCR)", te: "కాగితపు రికార్డు డిజిటల్ చేయండి (OCR)" },
  recordsFilterAll: { en: "All Records", hi: "सभी रिकॉर्ड", te: "అన్ని రికార్డులు" },
  recordsFilterLab: { en: "Lab Reports", hi: "लैब रिपोर्ट", te: "ల్యాబ్ రిపోర్టులు" },
  recordsFilterVisit: { en: "PHC Visits", hi: "PHC विजिट", te: "PHC సందర్శనలు" },
  recordsFilterOcr: { en: "OCR Digitized", hi: "OCR डिजिटल", te: "OCR డిజిటల్" },
  recordsSearchPh: { en: "Search diagnoses, doctors...", hi: "बीमारी, डॉक्टर खोजें...", te: "వ్యాధులు, డాక్టర్లు వెతకండి..." },
  recordsOcrModalTitle: { en: "Digitise Paper Prescription (OCR)", hi: "कागज़ी पर्चा डिजिटल करें (OCR)", te: "కాగితపు ప్రిస్క్రిప్షన్ డిజిటల్ చేయండి (OCR)" },
  recordsOcrUploadTitle: { en: "Upload Paper Slip / Doctor Prescription", hi: "कागज़ी पर्ची / डॉक्टर का पर्चा अपलोड करें", te: "కాగితపు చీటీ / డాక్టర్ ప్రిస్క్రిప్షన్ అప్‌లోడ్ చేయండి" },
  recordsOcrUploadHint: { en: "Supports JPG, PNG photos or scanned hospital documents", hi: "JPG, PNG फोटो या स्कैन किए अस्पताल के दस्तावेज़ समर्थित", te: "JPG, PNG ఫోటోలు లేదా స్కాన్ చేసిన ఆసుపత్రి డాక్యుమెంట్లు సపోర్ట్" },
  recordsOcrChooseBtn: { en: "Choose Photo", hi: "फोटो चुनें", te: "ఫోటో ఎంచుకోండి" },
  recordsOcrSimulateBtn: { en: "Simulate Sample Slip", hi: "सैंपल पर्ची देखें", te: "నమూనా చీటీ చూడండి" },
  recordsOcrProcessing: { en: "Extracting and parsing clinical entities with OCR...", hi: "OCR से विवरण निकाला जा रहा है...", te: "OCR ద్వారా వివరాలు సేకరించబడుతున్నాయి..." },
  recordsOcrWarning: { en: "⚠️ Unverified OCR Output — Please verify extracted details before saving", hi: "⚠️ असत्यापित OCR आउटपुट — सहेजने से पहले विवरण जांच लें", te: "⚠️ ధృవీకరించని OCR అవుట్‌పుట్ — సేవ్ చేయడానికి ముందు వివరాలు తనిఖీ చేయండి" },
  recordsOcrTitleLabel: { en: "Record Title / Diagnosis", hi: "रिकॉर्ड शीर्षक / निदान", te: "రికార్డు శీర్షిక / నిదానం" },
  recordsOcrFacilityLabel: { en: "Facility", hi: "अस्पताल / केंद्र", te: "ఆసుపత్రి / కేంద్రం" },
  recordsOcrDateLabel: { en: "Date", hi: "तारीख", te: "తేదీ" },
  recordsOcrDoctorLabel: { en: "Doctor Name", hi: "डॉक्टर का नाम", te: "డాక్టర్ పేరు" },
  recordsOcrNotesLabel: { en: "Clinical Notes & Prescriptions", hi: "क्लिनिकल नोट्स और दवाएं", te: "క్లినికల్ నోట్స్ & ప్రిస్క్రిప్షన్లు" },
  recordsOcrSaveBtn: { en: "Save to Longitudinal Timeline", hi: "स्वास्थ्य टाइमलाइन में सहेजें", te: "ఆరోగ్య టైమ్‌లైన్‌లో సేవ్ చేయండి" },
  aptsDesc: { en: "Schedule outpatient visits, reserve queue slots, and receive instant digital OPD tokens.", hi: "ओपीडी विजिट तय करें, कतार स्लॉट रिजर्व करें और तुरंत डिजिटल टोकन पाएं।", te: "అవుట్‌పేషెంట్ సందర్శనలు షెడ్యూల్ చేసి, క్యూ స్లాట్లు రిజర్వ్ చేసి, తక్షణ డిజిటల్ OPD టోకెన్లు పొందండి." },
  aptsBookTitle: { en: "Book a New Visit", hi: "नई विजिट बुक करें", te: "కొత్త సందర్శన బుక్ చేయండి" },
  aptsInstantBadge: { en: "Instant Token", hi: "तुरंत टोकन", te: "తక్షణ టోకెన్" },
  aptsFacilityLabel: { en: "Healthcare Facility", hi: "स्वास्थ्य केंद्र", te: "ఆరోగ్య కేంద్రం" },
  aptsFacPhc: { en: "Primary Health Centre (PHC) Kondapur (1.4 km)", hi: "प्राथमिक स्वास्थ्य केंद्र (PHC) कोंडापुर (1.4 किमी)", te: "ప్రాథమిక ఆరోగ్య కేంద్రం (PHC) కొండాపూర్ (1.4 కి.మీ)" },
  aptsFacArea: { en: "Area Hospital Shankarpally (8.2 km)", hi: "एरिया अस्पताल शंकरपल्ली (8.2 किमी)", te: "ఏరియా ఆసుపత్రి శంకర్‌పల్లి (8.2 కి.మీ)" },
  aptsFacDist: { en: "District Referral Hospital Chevella (16 km)", hi: "जिला रेफरल अस्पताल शेवेला (16 किमी)", te: "జిల్లా రిఫరల్ ఆసుపత్రి చెవెళ్ల (16 కి.మీ)" },
  aptsDeptLabel: { en: "Clinical Department", hi: "विभाग (Department)", te: "విభాగం (Department)" },
  aptsDeptOpd: { en: "General Outpatient (OPD)", hi: "सामान्य बाह्य रोगी (OPD)", te: "జనరల్ అవుట్‌పేషెంట్ (OPD)" },
  aptsDeptNcd: { en: "NCD & Chronic Care (Diabetes/BP)", hi: "दीर्घकालिक देखभाल (शुगर/बीपी)", te: "దీర్ఘకాలిక సంరక్షణ (షుగర్/BP)" },
  aptsDeptMch: { en: "Maternal & Child Health (MCH)", hi: "माता और शिशु स्वास्थ्य (MCH)", te: "మాతృ & శిశు ఆరోగ్యం (MCH)" },
  aptsDeptOrtho: { en: "Physiotherapy & Ortho", hi: "फिजियोथेरेपी और हड्डी रोग (Ortho)", te: "ఫిజియోథెరపీ & ఎముకలు (Ortho)" },
  aptsDateLabel: { en: "Date", hi: "तारीख", te: "తేదీ" },
  aptsTimeLabel: { en: "Preferred Time Slot", hi: "समय चुनें (Time Slot)", te: "సమయం ఎంచుకోండి (Time Slot)" },
  aptsConfirmBtn: { en: "Confirm & Generate Token", hi: "पक्का करें और टोकन पाएं", te: "నిర్ధారించి టోకెన్ పొందండి" },
  aptsTokensTitle: { en: "Your Active Tokens", hi: "आपके सक्रिय टोकन", te: "మీ యాక్టివ్ టోకెన్లు" },
  consentDesc: { en: "ABDM-aligned patient data sovereign control. You decide which doctors, ASHA workers, and hospitals can view your health records.", hi: "ABDM-अनुरूप मरीज़ डेटा नियंत्रण। आप तय करते हैं कि कौन से डॉक्टर, आशा कार्यकर्ता और अस्पताल आपके रिकॉर्ड देख सकते हैं।", te: "ABDM-అనుకూల రోగి డేటా నియంత్రణ. ఏ డాక్టర్లు, ఆశా కార్యకర్తలు, ఆసుపత్రులు మీ రికార్డులు చూడవచ్చో మీరే నిర్ణయిస్తారు." },
  consentBannerTitle: { en: "Encrypted & Sovereign Patient Record Storage", hi: "एन्क्रिप्टेड और सुरक्षित मरीज़ रिकॉर्ड स्टोरेज", te: "ఎన్‌క్రిప్టెడ్ & సురక్షిత రోగి రికార్డు నిల్వ" },
  consentBannerText: { en: "In this demonstration POC, all records are encrypted and stored locally in your browser’s IndexedDB. No medical records can be shared with external providers without explicit cryptographic or verbal consent tokens.", hi: "इस डेमो POC में, सभी रिकॉर्ड एन्क्रिप्ट होकर आपके ब्राउज़र के IndexedDB में सुरक्षित रहते हैं। आपकी सहमति टोकन के बिना कोई रिकॉर्ड बाहर साझा नहीं होता।", te: "ఈ డెమో POCలో, అన్ని రికార్డులు ఎన్‌క్రిప్ట్ చేయబడి మీ బ్రౌజర్ IndexedDBలో సురక్షితంగా ఉంటాయి. మీ సమ్మతి టోకెన్ లేకుండా ఎలాంటి రికార్డులు బయటికి పంపబడవు." },
  consentActiveTitle: { en: "Active Provider Access Permissions", hi: "सक्रिय प्रदाता एक्सेस अनुमतियां", te: "యాక్టివ్ ప్రొవైడర్ యాక్సెస్ అనుమతులు" },
  consentGrantTitle: { en: "Grant Access to a New Healthcare Provider", hi: "नए डॉक्टर / अस्पताल को एक्सेस दें", te: "కొత్త వైద్య ప్రొవైడర్‌కు యాక్సెస్ ఇవ్వండి" },
  consentGrantDesc: { en: "Authorize another doctor, specialist clinic, or referral hospital to view your longitudinal history for a specified time window.", hi: "किसी अन्य डॉक्टर, विशेषज्ञ क्लीनिक या रेफरल अस्पताल को तय समय के लिए अपना स्वास्थ्य इतिहास देखने की अनुमति दें।", te: "మరో డాక్టర్, స్పెషలిస్ట్ క్లినిక్ లేదా రిఫరల్ ఆసుపత్రికి నిర్దిష్ట కాలానికి మీ ఆరోగ్య చరిత్ర చూసే అనుమతి ఇవ్వండి." },
  consentDoctorLabel: { en: "Doctor / Healthcare Facility", hi: "डॉक्टर / स्वास्थ्य केंद्र", te: "డాక్టర్ / ఆరోగ్య కేంద్రం" },
  consentDoctorPh: { en: "e.g. Dr. K. Sharma (District Hospital Chevella)", hi: "जैसे: डॉ. के. शर्मा (जिला अस्पताल शेवेला)", te: "ఉదా: డా. కె. శర్మ (జిల్లా ఆసుపత్రి చెవెళ్ల)" },
  consentDurationLabel: { en: "Access Duration", hi: "एक्सेस की अवधि", te: "యాక్సెస్ వ్యవధి" },
  consentDur1m: { en: "1 Month (Consultation window)", hi: "1 महीना (परामर्श अवधि)", te: "1 నెల (కన్సల్టేషన్ వ్యవధి)" },
  consentDur6m: { en: "6 Months (Temporary Follow-up)", hi: "6 महीने (अस्थायी फॉलो-अप)", te: "6 నెలలు (తాత్కాలిక ఫాలో-అప్)" },
  consentDur1y: { en: "1 Year (Continuous Chronic Care)", hi: "1 साल (निरंतर दीर्घकालिक देखभाल)", te: "1 సంవత్సరం (నిరంతర దీర్ఘకాలిక సంరక్షణ)" },
  consentAuthorizeBtn: { en: "Authorize Provider Access", hi: "एक्सेस की अनुमति दें", te: "యాక్సెస్ అనుమతి ఇవ్వండి" },
  emgBannerTitle: { en: "EMERGENCY TRIAGE SIMULATOR (108 Integration)", hi: "आपातकालीन सिम्युलेटर (108 इंटीग्रेशन)", te: "అత్యవసర సిమ్యులేటర్ (108 ఇంటిగ్రేషన్)" },
  emgBannerText: { en: "Simulates real-time automated emergency dispatch, PHC notification, and medical profile broadcasting for critical rural incidents.", hi: "वास्तविक समय में स्वचालित आपातकालीन डिस्पैच, PHC सूचना और मेडिकल प्रोफ़ाइल प्रसारण का प्रदर्शन करता है।", te: "రియల్-టైమ్ ఆటోమేటెడ్ ఎమర్జెన్సీ డిస్ప్యాచ్, PHC నోటిఫికేషన్ మరియు మెడికల్ ప్రొఫైల్ బ్రాడ్‌కాస్టింగ్‌ను అనుకరిస్తుంది." },
  emgTitle: { en: "Critical Emergency Assistance", hi: "गंभीर आपातकालीन सहायता", te: "తీవ్ర అత్యవసర సహాయం" },
  emgPrompt: { en: "Press the SOS button below to transmit your instant GPS coordinates, Health ID, and critical allergy profile to 108 Emergency Ambulance Dispatch.", hi: "नीचे SOS बटन दबाएं — आपकी GPS लोकेशन, हेल्थ ID और एलर्जी जानकारी तुरंत 108 एम्बुलेंस को भेजी जाएगी।", te: "క్రింది SOS బటన్ నొక్కండి — మీ GPS లొకేషన్, హెల్త్ ID మరియు అలర్జీ వివరాలు వెంటనే 108 అంబులెన్స్‌కు పంపబడతాయి." },
  emgSosBtn: { en: "SOS 108", hi: "SOS 108", te: "SOS 108" },
  emgLocation: { en: "Kondapur (17.47° N, 78.35° E)", hi: "कोंडापुर (17.47° N, 78.35° E)", te: "కొండాపూర్ (17.47° N, 78.35° E)" },
  emgAbhaAttached: { en: "ABHA Profile Auto-Attached", hi: "आभा प्रोफ़ाइल अपने आप जुड़ी", te: "ఆభా ప్రొఫైల్ ఆటోమేటిక్‌గా జత చేయబడింది" },
  emgAmbulanceStatus: { en: "AMBULANCE 108 EN ROUTE", hi: "एम्बुलेंस 108 रास्ते में है", te: "అంబులెన్స్ 108 దారిలో ఉంది" },
  emgPriorityBadge: { en: "Priority 1 Active", hi: "प्राथमिकता 1 सक्रिय", te: "ప్రాధాన్యత 1 యాక్టివ్" },
  emgEtaLabel: { en: "Estimated Arrival", hi: "पहुंचने का अनुमानित समय", te: "చేరుకునే అంచనా సమయం" },
  emgVehicle: { en: "Vehicle: TS-07-EM-1082 (PHC Kondapur)", hi: "वाहन: TS-07-EM-1082 (PHC कोंडापुर)", te: "వాహనం: TS-07-EM-1082 (PHC కొండాపూర్)" },
  emgContactsLabel: { en: "Emergency Contacts Notified", hi: "आपातकालीन संपर्कों को सूचित किया गया", te: "అత్యవసర కాంటాక్టులకు తెలియజేయబడింది" },
  emgContactName: { en: "Ravi (Son) • +91 98480 54321", hi: "रवि (बेटा) • +91 98480 54321", te: "రవి (కుమారుడు) • +91 98480 54321" },
  emgSmsSent: { en: "SMS Alert Sent with Live Map Link", hi: "लाइव मैप लिंक के साथ SMS अलर्ट भेजा गया", te: "లైవ్ మ్యాప్ లింక్‌తో SMS అలర్ట్ పంపబడింది" },
  emgMapYou: { en: "You (Lakshmi Devi)", hi: "आप (लक्ष्मी देवी)", te: "మీరు (లక్ష్మీ దేవి)" },
  emgMapAmbulance: { en: "108 Ambulance", hi: "108 एम्बुलेंस", te: "108 అంబులెన్స్" },
  emgCancelBtn: { en: "Cancel Emergency Request (False Alarm)", hi: "आपातकालीन अनुरोध रद्द करें (गलत अलार्म)", te: "అత్యవసర అభ్యర్థన రద్దు చేయండి (తప్పు అలారం)" },
  emgCallBtn: { en: "Direct Call 108 Dispatch", hi: "108 डिस्पैच को सीधे कॉल करें", te: "108 డిస్ప్యాచ్‌కు డైరెక్ట్ కాల్ చేయండి" },
  profileDesc: { en: "Your citizen health identity, Ayushman Bharat Digital Mission (ABDM) card, and clinical flags.", hi: "आपकी नागरिक स्वास्थ्य पहचान, आयुष्मान भारत डिजिटल मिशन (ABDM) कार्ड और मेडिकल जानकारी।", te: "మీ పౌర ఆరోగ్య గుర్తింపు, ఆయుష్మాన్ భారత్ డిజిటల్ మిషన్ (ABDM) కార్డు మరియు క్లినికల్ వివరాలు." },
  profilePrintBtn: { en: "Print ABHA Card", hi: "आभा कार्ड प्रिंट करें", te: "ఆభా కార్డు ప్రింట్ చేయండి" },
  profileAbdmTitle: { en: "Ayushman Bharat Digital Mission", hi: "आयुष्मान भारत डिजिटल मिशन", te: "ఆయుష్మాన్ భారత్ డిజిటల్ మిషన్" },
  profileGovt: { en: "GOVERNMENT OF INDIA", hi: "भारत सरकार", te: "భారత ప్రభుత్వం" },
  profileVerifiedBadge: { en: "VERIFIED CITIZEN", hi: "सत्यापित नागरिक", te: "ధృవీకరించబడిన పౌరుడు" },
  profileAbhaLabel: { en: "ABHA NUMBER", hi: "आभा नंबर (ABHA)", te: "ఆభా నంబర్ (ABHA)" },
  profileHealthIdLabel: { en: "HEALTH ID", hi: "हेल्थ ID", te: "హెల్త్ ID" },
  profileBloodGroupLabel: { en: "BLOOD GROUP", hi: "ब्लड ग्रुप", te: "బ్లడ్ గ్రూప్" },
  profileClinicalTitle: { en: "Clinical Profile & Emergency Contacts", hi: "मेडिकल प्रोफ़ाइल और आपातकालीन संपर्क", te: "క్లినికల్ ప్రొఫైల్ & అత్యవసర కాంటాక్టులు" },
  profileCatchmentBadge: { en: "PHC Catchment: Kondapur", hi: "PHC क्षेत्र: कोंडापुर", te: "PHC పరిధి: కొండాపూర్" },
  profilePhoneLabel: { en: "Registered Phone Number", hi: "पंजीकृत फोन नंबर", te: "నమోదైన ఫోన్ నంబర్" },
  profileEmergencyLabel: { en: "Emergency Nominee & Contact", hi: "आपातकालीन संपर्क (नॉमिनी)", te: "అత్యవసర కాంటాక్ట్ (నామినీ)" },
  profileChronicLabel: { en: "Chronic Conditions Diagnosed", hi: "पुरानी बीमारियां (Chronic)", te: "దీర్ఘకాలిక వ్యాధులు (Chronic)" },
  profileAllergiesLabel: { en: "Known Allergies & Drug Adverse Flags", hi: "ज्ञात एलर्जी और दवा से खतरा", te: "తెలిసిన అలర్జీలు & మందుల ప్రమాద సంకేతాలు" },
  profileAshaLabel: { en: "Assigned Community ASHA Health Worker", hi: "नियुक्त आशा स्वास्थ्य कार्यकर्ता", te: "కేటాయించిన ఆశా ఆరోగ్య కార్యకర్త" },
  profileAshaName: { en: "Sunita Bai (HW-9021) • Kondapur Sector 3", hi: "सुनीता बाई (HW-9021) • कोंडापुर सेक्टर 3", te: "సునీత బాయి (HW-9021) • కొండాపూర్ సెక్టార్ 3" },
  profileCallAshaBtn: { en: "Call ASHA", hi: "आशा को कॉल करें", te: "ఆశాకు కాల్ చేయండి" },

  // ─── Doctor Workspace ────────────────────────────────────────────
  docDashSubtitle: { en: "Primary Health Centre (PHC) Kondapur • Active OPD Clinic Session", hi: "प्राथमिक स्वास्थ्य केंद्र (PHC) कोंडापुर • सक्रिय ओपीडी क्लिनिक सत्र", te: "ప్రాథమిక ఆరోగ్య కేంద్రం (PHC) కొండాపూర్ • యాక్టివ్ OPD క్లినిక్ సెషన్" },
  docDashQueueBtn: { en: "Priority Queue", hi: "प्राथमिकता कतार (Queue)", te: "ప్రాధాన్యతా క్యూ (Queue)" },
  docDashRxBtn: { en: "Write Prescription", hi: "नुस्खा लिखें (Prescription)", te: "ప్రిస్క్రిప్షన్ రాయండి" },
  docDashStatPatients: { en: "Registered Patients", hi: "पंजीकृत मरीज़", te: "నమోదైన రోగులు" },
  docDashStatQueue: { en: "Patients in Queue", hi: "कतार में मरीज़", te: "క్యూలో రోగులు" },
  docDashStatUrgent: { en: "Urgent / High Priority", hi: "अत्यावश्यक / उच्च प्राथमिकता", te: "అత్యవసరం / అధిక ప్రాధాన్యత" },
  docDashStatReferrals: { en: "Active Referrals", hi: "सक्रिय रेफरल", te: "యాక్టివ్ రిఫరల్స్" },
  docDashChartTriage: { en: "Queue Triage Distribution", hi: "कतार ट्रायज वितरण", te: "క్యూ ట్రయాజ్ పంపిణీ" },
  docDashBadgeRealtime: { en: "Real-Time", hi: "रियल-टाइम", te: "రియల్-టైమ్" },
  docDashChartLoad: { en: "Weekly PHC Consultation Load", hi: "साप्ताहिक PHC परामर्श भार", te: "వారపు PHC కన్సల్టేషన్ లోడ్" },
  docDashBadgeSync: { en: "Sync Active", hi: "सिंक सक्रिय", te: "సింక్ యాక్టివ్" },
  docDashQueueTitle: { en: "Live OPD Priority Queue (Doctor Controlled)", hi: "लाइव ओपीडी प्राथमिकता कतार (डॉक्टर नियंत्रित)", te: "లైవ్ OPD ప్రాధాన్యతా క్యూ (డాక్టర్ నియంత్రిత)" },
  docDashSearchPh: { en: "Search patient...", hi: "मरीज़ खोजें...", te: "రోగిని వెతకండి..." },
  docDashFullQueue: { en: "Full Queue", hi: "पूरी कतार", te: "పూర్తి క్యూ" },
  docDashThToken: { en: "Token", hi: "टोकन", te: "టోకెన్" },
  docDashThPatient: { en: "Patient Name", hi: "मरीज़ का नाम", te: "రోగి పేరు" },
  docDashThAge: { en: "Age / Gender", hi: "उम्र / लिंग", te: "వయస్సు / లింగం" },
  docDashThComplaint: { en: "Chief Complaint", hi: "मुख्य शिकायत", te: "ప్రధాన లక్షణం" },
  docDashThPriority: { en: "Priority Level", hi: "प्राथमिकता स्तर", te: "ప్రాధాన్యతా స్థాయి" },
  docDashThWait: { en: "Wait Time", hi: "प्रतीक्षा समय", te: "వేచి ఉండే సమయం" },
  docDashThAction: { en: "Action", hi: "कार्रवाई", te: "చర్య" },
  docDashSymptomsTitle: { en: "Patient-Reported Symptoms Awaiting Clinical Review", hi: "मरीज़ द्वारा रिपोर्ट किए गए लक्षण — नैदानिक समीक्षा लंबित", te: "రోగి నివేదించిన లక్షణాలు — క్లినికల్ సమీక్ష పెండింగ్" },
  docDashBadgeAction: { en: "Action Required", hi: "कार्रवाई आवश्यक", te: "చర్య అవసరం" },
  queueSubtitle: { en: "Human-led triage protocol. Doctor controls patient prioritization and examination sequence.", hi: "मानव-नियंत्रित ट्रायज प्रोटोकॉल। डॉक्टर मरीज़ की प्राथमिकता और जांच क्रम नियंत्रित करते हैं।", te: "మానవ నియంత్రిత ట్రయాజ్ ప్రోటోకాల్. రోగుల ప్రాధాన్యత మరియు పరీక్షా క్రమాన్ని డాక్టర్ నియంత్రిస్తారు." },
  queueFilterAll: { en: "All Patients", hi: "सभी मरीज़", te: "అన్ని రోగులు" },
  queueFilterEmergency: { en: "🚨 Emergency", hi: "🚨 आपातकालीन", te: "🚨 అత్యవసరం" },
  queueFilterHigh: { en: "⚠️ High Priority", hi: "⚠️ उच्च प्राथमिकता", te: "⚠️ అధిక ప్రాధాన్యత" },
  queueFilterRoutine: { en: "✓ Routine", hi: "✓ सामान्य", te: "✓ సాధారణం" },
  queueAddToken: { en: "Add Token", hi: "टोकन जोड़ें", te: "టోకెన్ జోడించండి" },
  queueThToken: { en: "Token #", hi: "टोकन #", te: "టోకెన్ #" },
  queueThPatient: { en: "Patient Name & ABHA", hi: "मरीज़ का नाम व आभा (ABHA)", te: "రోగి పేరు & ఆభా (ABHA)" },
  queueThDemo: { en: "Demographics", hi: "जनसांख्यिकी विवरण", te: "జనాభా వివరాలు" },
  queueThComplaint: { en: "Chief Complaint & Triage Signs", hi: "मुख्य शिकायत व ट्रायज संकेत", te: "ప్రధాన లక్షణం & ట్రయాజ్ సంకేతాలు" },
  queueThPriority: { en: "Priority Level (Doctor Override)", hi: "प्राथमिकता स्तर (डॉक्टर ओवरराइड)", te: "ప్రాధాన్యతా స్థాయి (డాక్టర్ ఓవర్‌రైడ్)" },
  queueThArrival: { en: "Arrival Time", hi: "आगमन समय", te: "రాక సమయం" },
  queueThWait: { en: "Est. Wait", hi: "अनुमानित प्रतीक्षा", te: "అంచనా వేటు సమయం" },
  queueThAction: { en: "Action", hi: "कार्रवाई", te: "చర్య" },
  patDirSubtitle: { en: "Search and view longitudinal EHRs across assigned rural catchment sub-centres.", hi: "आवंटित ग्रामीण उप-केंद्रों में मरीज़ों के दीर्घकालिक ईएचआर (EHR) खोजें और देखें।", te: "కేటాయించిన గ్రామీణ ఉప-కేంద్రాల్లో రోగుల దీర్ఘకాలిక EHRలను వెతకండి మరియు చూడండి." },
  patDirSearchPh: { en: "Search name, ABHA, village...", hi: "नाम, आभा, गाँव खोजें...", te: "పేరు, ఆభా, గ్రామం వెతకండి..." },
  patRecRiskBadge: { en: "High Risk", hi: "उच्च जोखिम", te: "అధిక ప్రమాదం" },
  patRecPrescribeBtn: { en: "Prescribe", hi: "नुस्खा लिखें", te: "ప్రిస్క్రైబ్ చేయండి" },
  patRecReferralBtn: { en: "Referral", hi: "रेफरल", te: "రిఫరల్" },
  patRecConsultBtn: { en: "Consult", hi: "परामर्श", te: "కన్సల్ట్" },
  patRecPrintBtn: { en: "Print Chart", hi: "चार्ट प्रिंट करें", te: "చార్ట్ ప్రింట్ చేయండి" },
  patRecAiTitle: { en: "Clinical AI Assistant — Longitudinal Health Summary", hi: "क्लिनिकल एआई सहायक — दीर्घकालिक स्वास्थ्य सारांश", te: "క్లినికల్ AI అసిస్టెంట్ — దీర్ఘకాలిక ఆరోగ్య సారాంశం" },
  patRecAiBadge: { en: "Human-in-the-Loop", hi: "मानव नियंत्रण में (Human-in-the-Loop)", te: "హ్యూమన్-ఇన్-ది-లూప్" },
  patRecAiFocus: { en: "Suggested Clinical Review Focus Areas:", hi: "सुझाए गए नैदानिक समीक्षा क्षेत्र:", te: "సూచించిన క్లినికల్ సమీక్షా క్షేత్రాలు:" },
  patRecAiDisclaimer: { en: "⚠️ <strong>AI-assisted documentation</strong>: Grounded in recorded vitals, symptoms, and lab reports. Final clinical diagnoses and prescriptions remain solely the legal responsibility of the consulting physician.", hi: "⚠️ <strong>एआई-सहायता दस्तावेज़ीकरण</strong>: दर्ज वाइटल्स, लक्षणों और लैब रिपोर्ट पर आधारित। अंतिम नैदानिक निदान और नुस्खे पूरी तरह से परामर्श करने वाले चिकित्सक की कानूनी जिम्मेदारी हैं।", te: "⚠️ <strong>AI-సహాయక డాక్యుమెంటేషన్</strong>: నమోదైన వైటల్స్, లక్షణాలు మరియు ల్యాబ్ నివేదికల ఆధారంగా. తుది నిదానాలు మరియు ప్రిస్క్రిప్షన్‌ల బాధ్యత పూర్తిగా సంప్రదించే వైద్యుడిదే." },
  patRecVitalsTitle: { en: "Recorded Vitals", hi: "दर्ज वाइटल्स", te: "నమోదైన వైటల్స్" },
  patRecVitalBp: { en: "Blood Pressure", hi: "रक्तचाप (BP)", te: "రక్తపోటు (BP)" },
  patRecVitalGlucose: { en: "Random Glucose", hi: "रैंडम ग्लूकोज़", te: "రాండమ్ గ్లూకోజ్" },
  patRecVitalSpo2: { en: "SpO2", hi: "SpO2 (ऑक्सीजन)", te: "SpO2 (ఆక్సిజన్)" },
  patRecVitalHr: { en: "Heart Rate", hi: "हृदय गति", te: "గుండె వేగం" },
  patRecProfileTitle: { en: "Clinical Profile & Flags", hi: "नैदानिक प्रोफ़ाइल व चेतावनी", te: "క్లినికల్ ప్రొఫైల్ & ఫ్లాగ్స్" },
  patRecBadgeSync: { en: "EHR Synced", hi: "EHR सिंक हुआ", te: "EHR సింక్ అయింది" },
  patRecChronicLabel: { en: "Chronic Conditions:", hi: "पुरानी बीमारियां:", te: "దీర్ఘకాలిక వ్యాధులు:" },
  patRecAllergiesLabel: { en: "Known Allergies:", hi: "ज्ञात एलर्जी:", te: "తెలిసిన అలర్జీలు:" },
  patRecBloodLabel: { en: "Blood Group:", hi: "रक्त समूह:", te: "రక్త గ్రూప్:" },
  patRecEmergencyLabel: { en: "Emergency Contact:", hi: "आपातकालीन संपर्क:", te: "అత్యవసర పరిచయం:" },
  patRecAshaLabel: { en: "Assigned ASHA Worker", hi: "नियुक्त आशा कार्यकर्ता", te: "కేటాయించిన ఆశా కార్యకర్త" },
  patRecAshaName: { en: "Sunita Bai (ASHA Kondapur Sector 3)", hi: "सुनीता बाई (आशा कोंडापुर सेक्टर 3)", te: "సునీత బాయ్ (ఆశా కొండాపూర్ సెక్టార్ 3)" },
  patRecSymptomsTitle: { en: "Patient-Reported Symptoms", hi: "मरीज़ द्वारा रिपोर्ट किए गए लक्षण", te: "రోగి నివేదించిన లక్షణాలు" },
  patRecNoteTitle: { en: "Add Doctor Clinical Note & Assessment", hi: "डॉक्टर का नैदानिक नोट व मूल्यांकन जोड़ें", te: "డాక్టర్ క్లినికల్ నోట్ & అంచనా జోడించండి" },
  patRecNoteLabel: { en: "Clinical Impression & Assessment", hi: "नैदानिक अभिप्राय व मूल्यांकन", te: "క్లినికల్ అభిప్రాయం & అంచనా" },
  patRecNotePh: { en: "e.g. Patient presents with dizziness and elevated BP. Initiating dietary sodium restriction and scheduled cardiology review...", hi: "जैसे: मरीज़ को चक्कर और बढ़ा हुआ बीपी है। नमक प्रतिबंध और कार्डियोलॉजी समीक्षा निर्धारित...", te: "ఉదా: రోగికి తలతిరుగుట మరియు పెరిగిన BP ఉంది. ఉప్పు తగ్గింపు మరియు కార్డియాలజీ సమీక్ష షెడ్యూల్..." },
  patRecNoteSave: { en: "Save Note to Longitudinal Record", hi: "नोट दीर्घकालिक रिकॉर्ड में सहेजें", te: "నోట్‌ను దీర్ఘకాలిక రికార్డులో సేవ్ చేయండి" },
  patRecTimelineTitle: { en: "Lifetime Longitudinal Medical Timeline", hi: "आजीवन दीर्घकालिक चिकित्सा टाइमलाइन", te: "జీవితకాల వైద్య కాలక్రమం (Timeline)" },
  consultLiveBadge: { en: "Encrypted WebRTC Teleconsultation Live", hi: "एन्क्रिप्टेड WebRTC टेलीकंसल्टेशन लाइव", te: "ఎన్‌క్రిప్టెడ్ WebRTC టెలీకన్సల్టేషన్ లైవ్" },
  consultSessionId: { en: "Session ID: TC-8492", hi: "सत्र ID: TC-8492", te: "సెషన్ ID: TC-8492" },
  consultEhrBtn: { en: "Open EHR History", hi: "EHR इतिहास खोलें", te: "EHR చరిత్ర తెరవండి" },
  consultPatientName: { en: "Lakshmi Devi", hi: "लक्ष्मी देवी", te: "లక్ష్మీ దేవి" },
  consultConnectedFrom: { en: "Connected from Kondapur Sub-Centre (ASHA Assisted: Sunita Bai)", hi: "कोंडापुर उप-केंद्र से जुड़ी (आशा सहायता: सुनीता बाई)", te: "కొండాపూర్ ఉప-కేంద్రం నుండి కనెక్ట్ (ఆశా సహాయం: సునీత బాయ్)" },
  consultLatency: { en: "Latency: 38ms • Audio/Video High-Def", hi: "विलंबता: 38ms • ऑडियो/वीडियो हाई-डेफ", te: "లేటెన్సీ: 38ms • ఆడియో/వీడియో హై-డెఫ్" },
  consultDoctorName: { en: "Dr. Ananya Rao", hi: "डॉ. अनन्या राव", te: "డాక్టర్ అనన్య రావు" },
  consultDoctorRole: { en: "PHC Medical Officer", hi: "PHC चिकित्सा अधिकारी", te: "PHC వైద్యాధికారి" },
  consultVitalsTitle: { en: "Live Field Vitals (Lakshmi Devi)", hi: "लाइव फ़ील्ड वाइटल्स (लक्ष्मी देवी)", te: "లైవ్ ఫీల్డ్ వైటల్స్ (లక్ష్మీ దేవి)" },
  consultVitalsBadge: { en: "Captured by ASHA Today", hi: "आज आशा द्वारा दर्ज", te: "ఈరోజు ఆశా నమోదు చేసింది" },
  consultVitalBp: { en: "Blood Pressure", hi: "रक्तचाप (BP)", te: "రక్తపోటు (BP)" },
  consultVitalSugar: { en: "Random Sugar", hi: "रैंडम शुगर", te: "రాండమ్ షుగర్" },
  consultVitalPulse: { en: "Pulse & SpO2", hi: "नाड़ी व SpO2", te: "పల్స్ & SpO2" },
  consultVitalAllergies: { en: "Allergies", hi: "एलर्जी", te: "అలర్జీలు" },
  consultNotesTitle: { en: "Clinical Notes & SOAP Documentation", hi: "नैदानिक नोट्स व SOAP दस्तावेज़ीकरण", te: "క్లినికల్ నోట్స్ & SOAP డాక్యుమెంటేషన్" },
  consultAutoSoap: { en: "Auto SOAP", hi: "ऑटो SOAP", te: "ఆటో SOAP" },
  consultNotesLabel: { en: "Clinical Notes / SOAP Findings", hi: "नैदानिक नोट्स / SOAP निष्कर्ष", te: "క్లినికల్ నోట్స్ / SOAP ఫలితాలు" },
  consultDictateBtn: { en: "Voice Dictate", hi: "वॉयस डिक्टेट", te: "వాయిస్ డిక్టేట్" },
  consultNotesPh: { en: "Document patient verbal answers, symptom duration, and clinical advice...", hi: "मरीज़ के मौखिक उत्तर, लक्षण अवधि और नैदानिक सलाह दर्ज करें...", te: "రోగి మౌఖిక సమాధానాలు, లక్షణ వ్యవధి మరియు క్లినికల్ సలహా నమోదు చేయండి..." },
  consultFollowupLabel: { en: "Follow-up & Patient Recommendation", hi: "फॉलो-अप व मरीज़ हेतु सिफारिश", te: "ఫాలో-అప్ & రోగి సిఫార్సు" },
  consultQuickActions: { en: "Quick Actions", hi: "त्वरित कार्रवाई", te: "త్వరిత చర్యలు" },
  consultIssueRx: { en: "Issue Rx", hi: "नुस्खा जारी करें (Rx)", te: "Rx జారీ చేయండి" },
  consultCreateRef: { en: "Create Referral", hi: "रेफरल बनाएं", te: "రిఫరల్ సృష్టించండి" },
  consultSaveBtn: { en: "Save Consultation & Complete Session", hi: "परामर्श सहेजें व सत्र पूर्ण करें", te: "కన్సల్టేషన్ సేవ్ చేసి సెషన్ పూర్తి చేయండి" },
  rxTitle: { en: "Clinical e-Prescription (Rx) Studio", hi: "क्लिनिकल ई-पर्चा (e-Rx) स्टूडियो", te: "క్లినికల్ e-ప్రిస్క్రిప్షన్ (Rx) స్టూడియో" },
  rxSubtitle: { en: "Issue digital prescriptions with automatic drug-allergy safety validation and instant EHR sync.", hi: "स्वचालित दवा-एलर्जी सुरक्षा जांच और त्वरित EHR सिंक के साथ डिजिटल नुस्खे जारी करें।", te: "ఆటోమేటిక్ మందుల అలర్జీ భద్రతా తనిఖీ మరియు తక్షణ EHR సింక్‌తో డిజిటల్ ప్రిస్క్రిప్షన్‌లు జారీ చేయండి." },
  rxPrintBtn: { en: "Print Official Rx Slip", hi: "आधिकारिक पर्चा प्रिंट करें", te: "అధికారిక Rx స్లిప్ ప్రింట్ చేయండి" },
  rxFormTitle: { en: "Generate Digital Prescription", hi: "डिजिटल नुस्खा बनाएं", te: "డిజిటల్ ప్రిస్క్రిప్షన్ రూపొందించండి" },
  rxFacilityBadge: { en: "PHC Kondapur", hi: "पीएचसी कोंडापुर", te: "PHC కొండాపూర్" },
  rxPatientLabel: { en: "Select Registered Patient <span class=\"required\">*</span>", hi: "पंजीकृत मरीज़ चुनें <span class=\"required\">*</span>", te: "నమోదైన రోగిని ఎంచుకోండి <span class=\"required\">*</span>" },
  rxDiagLabel: { en: "Clinical Diagnosis / ICD-10", hi: "नैदानिक निदान / ICD-10", te: "క్లినికల్ డయాగ్నోసిస్ / ICD-10" },
  rxMedsLabel: { en: "Prescribed Medications", hi: "निर्धारित दवाएं", te: "ప్రిస్క్రైబ్ చేసిన మందులు" },
  rxAddMedBtn: { en: "Add Medicine", hi: "दवा जोड़ें", te: "మందు జోడించండి" },
  rxMedNameLabel: { en: "Medicine Name & Generic Formulation", hi: "दवा का नाम व जेनेरिक फॉर्मूलेशन", te: "మందు పేరు & జెనరిక్ ఫార్ములేషన్" },
  rxMedNamePh: { en: "e.g. Tab Metformin HCl", hi: "जैसे: टैब मेटफॉर्मिन HCl", te: "ఉదా: ట్యాబ్ మెట్‌ఫార్మిన్ HCl" },
  rxDoseLabel: { en: "Dosage", hi: "खुराक", te: "డోసేజ్" },
  rxDosePh: { en: "e.g. 500 mg", hi: "जैसे: 500 मि.ग्रा.", te: "ఉదా: 500 mg" },
  rxFreqLabel: { en: "Frequency", hi: "आवृत्ति (कितनी बार)", te: "ఫ్రీక్వెన్సీ (ఎన్నిసార్లు)" },
  rxFreqOnce: { en: "Once daily (Morning)", hi: "दिन में एक बार (सुबह)", te: "రోజుకు ఒకసారి (ఉదయం)" },
  rxFreqTwice: { en: "Twice daily (1-0-1)", hi: "दिन में दो बार (1-0-1)", te: "రోజుకు రెండుసార్లు (1-0-1)" },
  rxFreqThrice: { en: "Thrice daily (1-1-1)", hi: "दिन में तीन बार (1-1-1)", te: "రోజుకు మూడుసార్లు (1-1-1)" },
  rxFreqSos: { en: "As needed (SOS)", hi: "आवश्यकतानुसार (SOS)", te: "అవసరమైనప్పుడు (SOS)" },
  rxDurationLabel: { en: "Duration", hi: "अवधि", te: "వ్యవధి" },
  rxDurationPh: { en: "e.g. 30 Days", hi: "जैसे: 30 दिन", te: "ఉదా: 30 రోజులు" },
  rxInstrLabel: { en: "Instructions / Food Timing", hi: "निर्देश / भोजन समय", te: "సూచనలు / ఆహార సమయం" },
  rxInstrPh: { en: "e.g. After meals", hi: "जैसे: भोजन के बाद", te: "ఉదా: భోజనం తర్వాత" },
  rxAdviceLabel: { en: "Doctor Special Clinical Instructions & Diet", hi: "डॉक्टर के विशेष नैदानिक निर्देश व आहार", te: "డాక్టర్ ప్రత్యేక క్లినికల్ సూచనలు & ఆహారం" },
  rxAdvicePh: { en: "e.g. Low sodium diet, 30 min brisk walking daily. Immediate PHC visit if systolic BP > 160.", hi: "जैसे: कम नमक का आहार, रोज़ 30 मिनट तेज़ चलना। सिस्टोलिक बीपी > 160 होने पर तुरंत PHC जाएं।", te: "ఉదా: తక్కువ ఉప్పు ఆహారం, రోజూ 30 నిమిషాలు నడక. సిస్టోలిక్ BP > 160 అయితే వెంటనే PHC కి రండి." },
  rxSignBtn: { en: "Sign & Issue Electronic Prescription", hi: "हस्ताक्षर करें व इलेक्ट्रॉनिक नुस्खा जारी करें", te: "సంతకం చేసి ఎలక్ట్రానిక్ ప్రిస్క్రిప్షన్ జారీ చేయండి" },
  rxGovt: { en: "GOVERNMENT OF TELANGANA", hi: "तेलंगाना सरकार", te: "తెలంగాణ ప్రభుత్వం" },
  rxPhcName: { en: "PRIMARY HEALTH CENTRE (PHC) KONDAPUR", hi: "प्राथमिक स्वास्थ्य केंद्र (PHC) कोंडापुर", te: "ప్రాథమిక ఆరోగ్య కేంద్రం (PHC) కొండాపూర్" },
  rxDistrict: { en: "District: Ranga Reddy • National Health Mission POC", hi: "जिला: रंगा रेड्डी • राष्ट्रीय स्वास्थ्य मिशन POC", te: "జిల్లా: రంగారెడ్డి • నేషనల్ హెల్త్ మిషన్ POC" },
  rxPrescriberLabel: { en: "Prescriber:", hi: "नुस्खा लेखक:", te: "ప్రిస్క్రైబర్:" },
  rxRegNo: { en: "Reg: TSMC-7842", hi: "रजि: TSMC-7842", te: "రిజి: TSMC-7842" },
  rxDateLabel: { en: "Date:", hi: "तारीख:", te: "తేదీ:" },
  rxSigBadge: { en: "Digital Signature Verified", hi: "डिजिटल हस्ताक्षर सत्यापित", te: "డిజిటల్ సంతకం ధృవీకరించబడింది" },
  rxPatNameLabel: { en: "Patient Name:", hi: "मरीज़ का नाम:", te: "రోగి పేరు:" },
  rxAgeLabel: { en: "Age / Gender:", hi: "उम्र / लिंग:", te: "వయస్సు / లింగం:" },
  rxHealthIdLabel: { en: "Health ID:", hi: "हेल्थ ID:", te: "హెల్త్ ID:" },
  rxAbhaLabel: { en: "ABHA:", hi: "आभा (ABHA):", te: "ఆభా (ABHA):" },
  rxDiagPreviewLabel: { en: "Diagnosis:", hi: "निदान:", te: "డయాగ్నోసిస్:" },
  rxMedOrders: { en: "MEDICATION ORDERS:", hi: "दवा आदेश:", te: "మందుల ఆర్డర్లు:" },
  rxAdvicePreview: { en: "Doctor's Advice:", hi: "डॉक्टर की सलाह:", te: "డాక్టర్ సలహా:" },
  rxSigLine: { en: "Medical Officer Signature", hi: "चिकित्सा अधिकारी हस्ताक्षर", te: "వైద్యాధికారి సంతకం" },
  rxHistoryTitle: { en: "Recent Prescriptions History", hi: "हालिया नुस्खों का इतिहास", te: "ఇటీవలి ప్రిస్క్రిప్షన్ల చరిత్ర" },
  refSubtitle: { en: "Transfer clinical responsibility and request specialized diagnostics with encrypted longitudinal EHR sharing.", hi: "एन्क्रिप्टेड दीर्घकालिक EHR साझाकरण के साथ नैदानिक जिम्मेदारी स्थानांतरित करें और विशेषज्ञ जांच का अनुरोध करें।", te: "ఎన్‌క్రిప్టెడ్ దీర్ఘకాలిక EHR షేరింగ్‌తో క్లినికల్ బాధ్యతను బదిలీ చేయండి మరియు స్పెషలైజ్డ్ డయాగ్నోస్టిక్స్ అభ్యర్థించండి." },
  refFormTitle: { en: "Initiate Clinical Referral", hi: "नैदानिक रेफरल शुरू करें", te: "క్లినికల్ రిఫరల్ ప్రారంభించండి" },
  refFacilityBadge: { en: "PHC Kondapur", hi: "पीएचसी कोंडापुर", te: "PHC కొండాపూర్" },
  refPatientLabel: { en: "Select Registered Patient <span class=\"required\">*</span>", hi: "पंजीकृत मरीज़ चुनें <span class=\"required\">*</span>", te: "నమోదైన రోగిని ఎంచుకోండి <span class=\"required\">*</span>" },
  refDestLabel: { en: "Destination Facility & Department", hi: "गंतव्य अस्पताल व विभाग", te: "గమ్య ఆసుపత్రి & విభాగం" },
  refDest1: { en: "District Hospital Chevella (Cardiology Dept)", hi: "जिला अस्पताल चेवेल्ला (कार्डियोलॉजी विभाग)", te: "జిల్లా ఆసుపత్రి చేవెళ్ళ (కార్డియాలజీ విభాగం)" },
  refDest2: { en: "Osmania General Hospital (Tertiary Nephrology / Endocrinology)", hi: "उस्मानिया जनरल अस्पताल (तृतीयक नेफ्रोलॉजी / एंडोक्रिनोलॉजी)", te: "ఉస్మానియా జనరల్ ఆసుపత్రి (టెర్షరీ నెఫ్రాలజీ / ఎండోక్రినాలజీ)" },
  refDest3: { en: "Area Hospital Shankarpally (General Surgery / Orthopaedics)", hi: "क्षेत्रीय अस्पताल शंकरपल्ली (सामान्य सर्जरी / ऑर्थोपेडिक्स)", te: "ఏరియా ఆసుపత్రి శంకర్‌పల్లి (జనరల్ సర్జరీ / ఆర్థోపెడిక్స్)" },
  refSpecLabel: { en: "Clinical Specialty", hi: "नैदानिक विशेषता", te: "క్లినికల్ స్పెషాలిటీ" },
  refPriorityLabel: { en: "Priority Level", hi: "प्राथमिकता स्तर", te: "ప్రాధాన్యతా స్థాయి" },
  refPriHigh: { en: "⚠️ High Priority (48-72 hrs)", hi: "⚠️ उच्च प्राथमिकता (48-72 घंटे)", te: "⚠️ అధిక ప్రాధాన్యత (48-72 గంటలు)" },
  refPriRoutine: { en: "✓ Routine Elective", hi: "✓ सामान्य नियोजित", te: "✓ సాధారణ ఎలక్టివ్" },
  refPriEmergency: { en: "🚨 Emergency Transfer", hi: "🚨 आपातकालीन स्थानांतरण", te: "🚨 అత్యవసర బదిలీ" },
  refReasonLabel: { en: "Clinical Reason & Case Summary for Specialist", hi: "विशेषज्ञ हेतु नैदानिक कारण व केस सारांश", te: "స్పెషలిస్ట్ కోసం క్లినికల్ కారణం & కేసు సారాంశం" },
  refReasonPh: { en: "e.g. Episodic dizziness, palpitations, and persistent borderline hypertension in diabetic patient.", hi: "जैसे: मधुमेह रोगी में समय-समय पर चक्कर, धड़कन और लगातार सीमावर्ती उच्च रक्तचाप।", te: "ఉదా: మధుమేహ రోగిలో అప్పుడప్పుడు తలతిరుగుట, గుండె దడ మరియు నిరంతర బార్డర్‌లైన్ అధిక రక్తపోటు." },
  refSubmitBtn: { en: "Transmit Digital Referral Record", hi: "डिजिटल रेफरल रिकॉर्ड भेजें", te: "డిజిటల్ రిఫరల్ రికార్డును పంపండి" },
  refListTitle: { en: "Active Outgoing Referrals", hi: "सक्रिय आउटगोइंग रेफरल", te: "యాక్టివ్ అవుట్‌గోయింగ్ రిఫరల్స్" },
  fuSubtitle: { en: "Schedule chronic disease recalls, post-hospitalization checkups, and ASHA field visit tasks.", hi: "पुरानी बीमारियों की रिकॉल, अस्पताल से छुट्टी के बाद की जांच और आशा फ़ील्ड विज़िट कार्य निर्धारित करें।", te: "దీర్ఘకాలిక వ్యాధి రీకాల్స్, డిశ్చార్జ్ తర్వాత తనిఖీలు మరియు ఆశా ఫీల్డ్ విజిట్ పనులను షెడ్యూల్ చేయండి." },
  fuFormTitle: { en: "Schedule Clinical Follow-up", hi: "नैदानिक फॉलो-अप निर्धारित करें", te: "క్లినికల్ ఫాలో-అప్ షెడ్యూల్ చేయండి" },
  fuBadgeProtocol: { en: "Care Protocol", hi: "देखभाल प्रोटोकॉल", te: "కేర్ ప్రోటోకాల్" },
  fuPatientLabel: { en: "Registered Patient <span class=\"required\">*</span>", hi: "पंजीकृत मरीज़ <span class=\"required\">*</span>", te: "నమోదైన రోగి <span class=\"required\">*</span>" },
  fuDateLabel: { en: "Scheduled Date <span class=\"required\">*</span>", hi: "निर्धारित तारीख <span class=\"required\">*</span>", te: "షెడ్యూల్ తేదీ <span class=\"required\">*</span>" },
  fuReasonLabel: { en: "Clinical Follow-up Objective & Vitals Target", hi: "नैदानिक फॉलो-अप उद्देश्य व वाइटल्स लक्ष्य", te: "క్లినికల్ ఫాలో-అప్ లక్ష్యం & వైటల్స్ టార్గెట్" },
  fuReasonPh: { en: "e.g. 2-week BP check & fasting glucose review after starting Metformin", hi: "जैसे: मेटफॉर्मिन शुरू करने के बाद 2-सप्ताह बीपी जांच व फास्टिंग ग्लूकोज़ समीक्षा", te: "ఉదా: మెట్‌ఫార్మిన్ ప్రారంభించిన తర్వాత 2-వారాల BP తనిఖీ & ఫాస్టింగ్ గ్లూకోజ్ సమీక్ష" },
  fuAshaLabel: { en: "Assign Field ASHA Worker for Home Visit", hi: "घर की विज़िट हेतु फ़ील्ड आशा कार्यकर्ता नियुक्त करें", te: "ఇంటి సందర్శన కోసం ఫీల్డ్ ఆశా కార్యకర్తను కేటాయించండి" },
  fuAsha1: { en: "Sunita Bai (ASHA Sector 3 - Kondapur)", hi: "सुनीता बाई (आशा सेक्टर 3 - कोंडापुर)", te: "సునీత బాయ్ (ఆశా సెక్టార్ 3 - కొండాపూర్)" },
  fuAsha2: { en: "Rekha Devi (ASHA Sector 2 - Shankarpally)", hi: "रेखा देवी (आशा सेक्टर 2 - शंकरपल्ली)", te: "రేఖా దేవి (ఆశా సెక్టార్ 2 - శంకర్‌పల్లి)" },
  fuSubmitBtn: { en: "Schedule & Dispatch Notification to ASHA", hi: "शेड्यूल करें व आशा को सूचना भेजें", te: "షెడ్యూల్ చేసి ఆశాకు నోటిఫికేషన్ పంపండి" },
  fuListTitle: { en: "Active Care Follow-ups", hi: "सक्रिय देखभाल फॉलो-अप", te: "యాక్టివ్ కేర్ ఫాలో-అప్‌లు" },

  // ─── ASHA Worker Portal ──────────────────────────────────────────
  workDashSubtitle: { en: "Kondapur Sub-Centre Sector 3 • Offline Field Health & Assisted Citizen Care", hi: "कोंडापुर उप-केंद्र सेक्टर 3 • ऑफ़लाइन फ़ील्ड स्वास्थ्य एवं नागरिक सहायता", te: "కొండాపూర్ సబ్-సెంటర్ సెక్టర్ 3 • ఆఫ్‌లైన్ ఫీల్డ్ హెల్త్ & పౌర సహాయం" },
  workDashRecordVisit: { en: "Record Field Visit", hi: "घर का दौरा दर्ज करें", te: "ఇంటి సందర్శన నమోదు చేయండి" },
  workDashSyncQueue: { en: "Sync Queue", hi: "सिंक कतार", te: "సింక్ క్యూ" },
  workDashStatHouseholds: { en: "Assigned Households", hi: "आवंटित परिवार (Households)", te: "కేటాయించిన కుటుంబాలు" },
  workDashStatCitizens: { en: "Registered Citizens", hi: "पंजीकृत नागरिक", te: "నమోదైన పౌరులు" },
  workDashStatHighRisk: { en: "High-Risk Follow-ups", hi: "उच्च जोखिम फॉलो-अप", te: "అధిక ప్రమాద ఫాలో-అప్‌లు" },
  workDashStatOffline: { en: "Offline Queued Records", hi: "ऑफ़लाइन कतार रिकॉर्ड", te: "ఆఫ్‌లైన్ క్యూ రికార్డులు" },
  workDashAssistDesc: { en: "Help elderly or illiterate citizens view records with verbal consent", hi: "वरिष्ठ या अशिक्षित नागरिकों को मौखिक सहमति से रिकॉर्ड देखने में मदद करें", te: "వృద్ధులు లేదా నిరక్షరాస్య పౌరులకు మౌఖిక సమ్మతితో రికార్డులు చూపించండి" },
  workDashVitalsDesc: { en: "Capture BP, Blood Sugar, SpO2 & symptoms at patient household", hi: "मरीज़ के घर पर बीपी, शुगर, SpO2 और लक्षण दर्ज करें", te: "రోగి ఇంటి వద్ద BP, షుగర్, SpO2 & లక్షణాలు నమోదు చేయండి" },
  workDashVoiceDesc: { en: "Record quick audio visit observations in Hindi or Telugu", hi: "हिंदी या तेलुगु में त्वरित ऑडियो विज़िट नोट रिकॉर्ड करें", te: "తెలుగు లేదా హిందీలో త్వరిత ఆడియో విజిట్ నోట్స్ రికార్డ్ చేయండి" },
  workDashRosterTitle: { en: "Priority Village Households for Today", hi: "आज के प्राथमिकता ग्राम परिवार", te: "నేటి ప్రాధాన్యత గ్రామ కుటుంబాలు" },
  workDashRosterBadge: { en: "Sector 3 Roster", hi: "सेक्टर 3 सूची", te: "సెక్టర్ 3 జాబితా" },
  workDashColCitizen: { en: "Citizen Name", hi: "नागरिक का नाम", te: "పౌరుని పేరు" },
  workDashColHealthId: { en: "Health ID & ABHA", hi: "हेल्थ ID एवं ABHA", te: "హెల్త్ ID & ABHA" },
  workDashColVillage: { en: "Village / Sector", hi: "गाँव / सेक्टर", te: "గ్రామం / సెక్టర్" },
  workDashColRisk: { en: "Risk Category", hi: "जोखिम श्रेणी", te: "ప్రమాద వర్గం" },
  workDashColLastVital: { en: "Last Vital Check", hi: "अंतिम वाइटल्स जांच", te: "చివరి వైటల్స్ తనిఖీ" },
  workDashColActions: { en: "Field Actions", hi: "फ़ील्ड क्रियाएं", te: "ఫీల్డ్ చర్యలు" },
  workPatSubtitle: { en: "Catchment households under ASHA Worker Sunita Bai (Kondapur Sector 3).", hi: "आशा कार्यकर्ता सुनीता बाई के अंतर्गत परिवार (कोंडापुर सेक्टर 3)।", te: "ఆశా కార్యకర్త సునీతా బాయి పరిధిలోని కుటుంబాలు (కొండాపూర్ సెక్టర్ 3)." },
  workPatSearchPh: { en: "Search by name, Health ID...", hi: "नाम या हेल्थ ID से खोजें...", te: "పేరు, హెల్త్ ID ద్వారా వెతకండి..." },
  assistSubtitle: { en: "Assisting rural, non-literate, or elderly citizens to navigate their health records with explicit verbal consent.", hi: "ग्रामीण, अशिक्षित या वरिष्ठ नागरिकों को स्पष्ट मौखिक सहमति के साथ उनके स्वास्थ्य रिकॉर्ड देखने में सहायता।", te: "గ్రామీణ, నిరక్షరాస్య లేదా వృద్ధ పౌరులకు స్పష్టమైన మౌఖిక సమ్మతితో వారి ఆరోగ్య రికార్డులను చూడటంలో సహాయం." },
  assistSessionTitle: { en: "Initiate Assisted Field Session", hi: "सहायता प्राप्त फ़ील्ड सत्र शुरू करें", te: "సహాయక ఫీల్డ్ సెషన్ ప్రారంభించండి" },
  assistWorkerMeta: { en: "ASHA Community Worker: <strong>Sunita Bai (HW-9021)</strong>", hi: "आशा कार्यकर्ता: <strong>सुनीता बाई (HW-9021)</strong>", te: "ఆశా కమ్యూనిటీ వర్కర్: <strong>సునీతా బాయి (HW-9021)</strong>" },
  assistCitizenLabel: { en: "Select Citizen / Patient <span class=\"required\">*</span>", hi: "नागरिक / मरीज़ चुनें <span class=\"required\">*</span>", te: "పౌరుడు / రోగిని ఎంచుకోండి <span class=\"required\">*</span>" },
  assistConsentTitle: { en: "Citizen Verbal Consent & Audit Protocol", hi: "नागरिक मौखिक सहमति एवं ऑडिट प्रोटोकॉल", te: "పౌరుల మౌఖిక సమ్మతి & ఆడిట్ ప్రోటోకాల్" },
  assistConsentText: { en: "I confirm that I have explained the purpose in the citizen’s local language (Hindi/Telugu), and they have granted explicit verbal consent to view and update their longitudinal records during this household visit.", hi: "मैं पुष्टि करती हूं कि मैंने नागरिक की स्थानीय भाषा (हिंदी/तेलुगु) में उद्देश्य समझाया है, और उन्होंने इस घर के दौरे के दौरान अपने रिकॉर्ड देखने व अपडेट करने की स्पष्ट मौखिक सहमति दी है।", te: "పౌరుని స్థానిక భాషలో (తెలుగు/హిందీ) ఉద్దేశ్యం వివరించాను మరియు ఈ ఇంటి సందర్శనలో వారి రికార్డులను చూడటానికి, అప్‌డేట్ చేయటానికి స్పష్టమైన మౌఖిక సమ్మతి ఇచ్చారని నిర్ధారిస్తున్నాను." },
  assistLaunchBtn: { en: "Launch Assisted Patient Workspace", hi: "सहायता प्राप्त मरीज़ वर्कस्पेस खोलें", te: "సహాయక రోగి వర్క్‌స్పేస్ తెరవండి" },
  visitSubtitle: { en: "Record physical vitals, blood glucose, and symptom observations directly at the patient’s home.", hi: "मरीज़ के घर पर सीधे वाइटल्स, ब्लड ग्लूकोज़ और लक्षणों का अवलोकन दर्ज करें।", te: "రోగి ఇంటి వద్ద నేరుగా వైటల్స్, బ్లడ్ గ్లూకోజ్ మరియు లక్షణాల పరిశీలనలు నమోదు చేయండి." },
  visitPatientLabel: { en: "Select Citizen / Household Patient <span class=\"required\">*</span>", hi: "नागरिक / परिवार का मरीज़ चुनें <span class=\"required\">*</span>", te: "పౌరుడు / కుటుంబ రోగిని ఎంచుకోండి <span class=\"required\">*</span>" },
  visitVitalsTitle: { en: "Vital Sign Measurements", hi: "वाइटल्स माप (Vital Signs)", te: "వైటల్స్ కొలతలు (Vital Signs)" },
  visitBpLabel: { en: "Blood Pressure (Systolic / Diastolic mmHg)", hi: "ब्लड प्रेशर (सिस्टोलिक / डायस्टोलिक mmHg)", te: "బ్లడ్ ప్రెషర్ (సిస్టోలిక్ / డయాస్టోలిక్ mmHg)" },
  visitSysPh: { en: "Systolic (e.g. 140)", hi: "सिस्टोलिक (जैसे 140)", te: "సిస్టోలిక్ (ఉదా. 140)" },
  visitDiaPh: { en: "Diastolic (e.g. 90)", hi: "डायस्टोलिक (जैसे 90)", te: "డయాస్టోలిక్ (ఉదా. 90)" },
  visitSugarLabel: { en: "Random Blood Glucose (mg/dL)", hi: "रैंडम ब्लड ग्लूकोज़ (mg/dL)", te: "రాండమ్ బ్లడ్ గ్లూకోజ్ (mg/dL)" },
  visitSugarPh: { en: "e.g. 165", hi: "जैसे 165", te: "ఉదా. 165" },
  visitHrLabel: { en: "Heart Rate (bpm)", hi: "हृदय गति (bpm)", te: "హృదయ స్పందన (bpm)" },
  visitSpo2Label: { en: "Oxygen SpO2 (%)", hi: "ऑक्सीजन SpO2 (%)", te: "ఆక్సిజన్ SpO2 (%)" },
  visitTempLabel: { en: "Temperature (°F)", hi: "तापमान (°F)", te: "ఉష్ణోగ్రత (°F)" },
  visitObsTitle: { en: "Symptom & Household Observations", hi: "लक्षण एवं घरेलू अवलोकन", te: "లక్షణాలు & గృహ పరిశీలనలు" },
  visitNotesLabel: { en: "Chief Complaint & Citizen Description", hi: "मुख्य शिकायत एवं नागरिक का विवरण", te: "ప్రధాన ఫిర్యాదు & పౌరుని వివరణ" },
  visitNotesPh: { en: "e.g. Patient mentioned feeling lightheaded when getting out of bed. Medication compliance is good.", hi: "जैसे: मरीज़ ने बिस्तर से उठते समय हल्का चक्कर बताया। दवा नियमित रूप से ले रहे हैं।", te: "ఉదా: రోగి మంచం నుండి లేవగా తల తిరుగుతున్నట్లు తెలిపారు. మందులు క్రమం తప్పకుండా తీసుకుంటున్నారు." },
  visitSaveBtn: { en: "Save & Sync Visit Record", hi: "दौरा रिकॉर्ड सहेजें और सिंक करें", te: "సందర్శన రికార్డు సేవ్ & సింక్ చేయండి" },
  vitalSubtitle: { en: "Monitor blood pressure, blood glucose, and temperature patterns across village households.", hi: "ग्राम परिवारों में ब्लड प्रेशर, ब्लड ग्लूकोज़ और तापमान के पैटर्न की निगरानी करें।", te: "గ్రామ కుటుంబాల్లో బ్లడ్ ప్రెషర్, బ్లడ్ గ్లూకోజ్ మరియు ఉష్ణోగ్రత ధోరణులను పర్యవేక్షించండి." },
  vitalRecordBtn: { en: "Record Field Checkup", hi: "फ़ील्ड जांच दर्ज करें", te: "ఫీల్డ్ తనిఖీ నమోదు చేయండి" },
  vitalRefBp: { en: "<strong>Blood Pressure:</strong> Normal (&lt; 120/80) • Elevated (120-139 / 80-89) • <span style=\"color:var(--status-emergency); font-weight:700;\">Stage 2 / Urgent (≥ 140/90)</span>", hi: "<strong>ब्लड प्रेशर:</strong> सामान्य (&lt; 120/80) • बढ़ा हुआ (120-139 / 80-89) • <span style=\"color:var(--status-emergency); font-weight:700;\">स्टेज 2 / तत्काल (≥ 140/90)</span>", te: "<strong>బ్లడ్ ప్రెషర్:</strong> సాధారణం (&lt; 120/80) • ఎక్కువ (120-139 / 80-89) • <span style=\"color:var(--status-emergency); font-weight:700;\">స్టేజ్ 2 / అత్యవసరం (≥ 140/90)</span>" },
  vitalRefSugar: { en: "<strong>Random Sugar:</strong> Normal (&lt; 140 mg/dL) • <span style=\"color:var(--status-high); font-weight:700;\">High (&gt; 160 mg/dL)</span>", hi: "<strong>रैंडम शुगर:</strong> सामान्य (&lt; 140 mg/dL) • <span style=\"color:var(--status-high); font-weight:700;\">अधिक (&gt; 160 mg/dL)</span>", te: "<strong>రాండమ్ షుగర్:</strong> సాధారణం (&lt; 140 mg/dL) • <span style=\"color:var(--status-high); font-weight:700;\">ఎక్కువ (&gt; 160 mg/dL)</span>" },
  vitalRefSpo2: { en: "<strong>SpO2:</strong> Normal (≥ 95%) • <span style=\"color:var(--status-emergency); font-weight:700;\">Hypoxia (&lt; 92%)</span>", hi: "<strong>SpO2:</strong> सामान्य (≥ 95%) • <span style=\"color:var(--status-emergency); font-weight:700;\">ऑक्सीजन कमी (&lt; 92%)</span>", te: "<strong>SpO2:</strong> సాధారణం (≥ 95%) • <span style=\"color:var(--status-emergency); font-weight:700;\">హైపాక్సియా (&lt; 92%)</span>" },
  vitalTableTitle: { en: "Recent Field Checkups (Lakshmi Devi - LP-10234)", hi: "हालिया फ़ील्ड जांचें (लक्ष्मी देवी - LP-10234)", te: "ఇటీవలి ఫీల్డ్ తనిఖీలు (లక్ష్మి దేవి - LP-10234)" },
  vitalNewCheckBtn: { en: "+ New Vitals Check", hi: "+ नई वाइटल्स जांच", te: "+ కొత్త వైటల్స్ తనిఖీ" },
  vitalColDate: { en: "Date & Time", hi: "तारीख़ एवं समय", te: "తేదీ & సమయం" },
  vitalColBp: { en: "BP (mmHg)", hi: "बीपी (mmHg)", te: "BP (mmHg)" },
  vitalColSugar: { en: "Random Sugar", hi: "रैंडम शुगर", te: "రాండమ్ షుగర్" },
  vitalColSpo2: { en: "SpO2", hi: "SpO2", te: "SpO2" },
  vitalColPulse: { en: "Pulse", hi: "पल्स", te: "పల్స్" },
  vitalColBy: { en: "Recorded By", hi: "दर्जकर्ता", te: "నమోదు చేసినవారు" },
  vitalColStatus: { en: "Clinical Status Alert", hi: "क्लिनिकल स्थिति अलर्ट", te: "క్లినికల్ స్థితి అలర్ట్" },
  workVoiceSubtitle: { en: "Speak in Telugu, Hindi, or English during household visits to record rapid clinical observations.", hi: "घर के दौरे के दौरान तेलुगु, हिंदी या अंग्रेजी में बोलकर त्वरित क्लिनिकल अवलोकन दर्ज करें।", te: "ఇంటి సందర్శనల్లో తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో మాట్లాడి త్వరిత క్లినికల్ పరిశీలనలు నమోదు చేయండి." },
  workVoicePatLabel: { en: "Citizen / Household Patient", hi: "नागरिक / परिवार का मरीज़", te: "పౌరుడు / కుటుంబ రోగి" },
  workVoiceLangLabel: { en: "Voice Language:", hi: "बोलने की भाषा:", te: "మాట్లాడే భాష:" },
  workVoiceLangTe: { en: "తెలుగు (Telugu)", hi: "तेलुगु (Telugu)", te: "తెలుగు (Telugu)" },
  workVoiceLangHi: { en: "हिन्दी (Hindi)", hi: "हिन्दी (Hindi)", te: "హిందీ (Hindi)" },
  workVoiceLangEn: { en: "English (India)", hi: "अंग्रेजी (English)", te: "ఇంగ్లీష్ (English)" },
  workVoiceSamplesTitle: { en: "Or click a sample field observation:", hi: "या कोई नमूना फ़ील्ड अवलोकन चुनें:", te: "లేదా నమూనా ఫీల్డ్ పరిశీలన క్లిక్ చేయండి:" },
  workVoiceSample1: { en: "\"రక్తపోటు ఎక్కువగా ఉంది\" (Telugu)", hi: "\"రక్తపోటు ఎక్కువగా ఉంది\" (Telugu)", te: "\"రక్తపోటు ఎక్కువగా ఉంది\" (Telugu)" },
  workVoiceSample2: { en: "\"दवा नियमित रूप से ले रहे हैं\" (Hindi)", hi: "\"दवा नियमित रूप से ले रहे हैं\" (Hindi)", te: "\"दवा नियमित रूप से ले रहे हैं\" (Hindi)" },
  workVoiceSample3: { en: "\"Patient compliant, BP slightly elevated\"", hi: "\"मरीज़ दवा ले रहा है, बीपी थोड़ा बढ़ा हुआ\"", te: "\"రోగి మందులు వాడుతున్నారు, BP కొద్దిగా ఎక్కువ\"" },
  workVoiceTranscriptTitle: { en: "Transcribed ASHA Field Note", hi: "लिखित आशा फ़ील्ड नोट", te: "రాయబడిన ఆశా ఫీల్డ్ నోట్" },
  workVoiceListening: { en: "Listening to Field Note...", hi: "फ़ील्ड नोट सुना जा रहा है...", te: "ఫీల్డ్ నోట్ వింటున్నాం..." },
  workVoiceTapToRecord: { en: "Tap to Record Voice Note", hi: "वॉयस नोट रिकॉर्ड करने के लिए टैप करें", te: "వాయిస్ నోట్ రికార్డ్ చేయడానికి నొక్కండి" },
  workVoiceTryAgain: { en: "Try Again", hi: "फिर से प्रयास करें", te: "మళ్లీ ప్రయత్నించండి" },
  workVoiceSaveBtn: { en: "Save to Patient Record", hi: "मरीज़ रिकॉर्ड में सहेजें", te: "రోగి రికార్డులో సేవ్ చేయండి" },
  syncSubtitle: { en: "Manage records collected in zero-connectivity rural zones and sync them seamlessly to the central PHC server.", hi: "बिना नेटवर्क वाले ग्रामीण क्षेत्रों में एकत्रित रिकॉर्ड प्रबंधित करें और केंद्रीय PHC सर्वर पर सिंक करें।", te: "నెట్‌వర్క్ లేని గ్రామీణ ప్రాంతాల్లో సేకరించిన రికార్డులను నిర్వహించి కేంద్ర PHC సర్వర్‌కు సింక్ చేయండి." },
  syncQueueSampleBtn: { en: "Queue Sample Visit", hi: "नमूना दौरा कतार में जोड़ें", te: "నమూనా సందర్శన క్యూలో చేర్చండి" },
  syncRecordsWaiting: { en: "Records Waiting to Sync", hi: "रिकॉर्ड सिंक की प्रतीक्षा में", te: "రికార్డులు సింక్ కోసం వేచి ఉన్నాయి" },
  syncOfflineNotice: { en: "All offline data is preserved safely in your device’s client-side IndexedDB engine.", hi: "सभी ऑफ़लाइन डेटा आपके डिवाइस के क्लाइंट-साइड IndexedDB में सुरक्षित रहता है।", te: "అన్ని ఆఫ్‌లైన్ డేటా మీ డివైస్ క్లయింట్-సైడ్ IndexedDBలో సురక్షితంగా ఉంటుంది." },
  syncOnlineBadge: { en: "Online (PHC Gateway Reachable)", hi: "ऑनलाइन (PHC गेटवे उपलब्ध)", te: "ఆన్‌లైన్ (PHC గేట్‌వే అందుబాటులో ఉంది)" },
  syncProgressLabel: { en: "Encrypting & Transmitting Payload...", hi: "एन्क्रिप्ट करके भेजा जा रहा है...", te: "ఎన్‌క్రిప్ట్ చేసి పంపుతోంది..." },
  syncPendingTitle: { en: "Pending Local Field Records", hi: "लंबित स्थानीय फ़ील्ड रिकॉर्ड", te: "పెండింగ్ లోకల్ ఫీల్డ్ రికార్డులు" },

  // ─── Shared Pages ────────────────────────────────────────────────
  a11ySubtitle: { en: "WCAG 2.1 AA compliant adjustments for low-vision, high-sunlight outdoor field usability, and elderly citizens.", hi: "WCAG 2.1 AA अनुरूप समायोजन — कम दृष्टि, तेज़ धूप में बाहरी उपयोग और वरिष्ठ नागरिकों के लिए।", te: "WCAG 2.1 AA అనుగుణమైన సర్దుబాట్లు — తక్కువ చూపు, ఎండలో ఫీల్డ్ వాడకం మరియు వృద్ధ పౌరుల కోసం." },
  a11yTextSizeLabel: { en: "Text Size & Target Scaling", hi: "टेक्स्ट आकार और बटन स्केलिंग", te: "టెక్స్ట్ సైజు & టార్గెట్ స్కేలింగ్" },
  a11yTextSizeDesc: { en: "Enlarges buttons, inputs, pills, and clinical record texts across all portal screens.", hi: "सभी पोर्टल स्क्रीन पर बटन, इनपुट और क्लिनिकल रिकॉर्ड टेक्स्ट बड़ा करता है।", te: "అన్ని పోర్టల్ స్క్రీన్‌లలో బటన్లు, ఇన్‌పుట్‌లు మరియు క్లినికల్ రికార్డు టెక్స్ట్‌ను పెద్దదిగా చేస్తుంది." },
  a11ySizeStandard: { en: "Standard (100%)", hi: "मानक (100%)", te: "ప్రామాణికం (100%)" },
  a11ySizeLarge: { en: "Large (115%)", hi: "बड़ा (115%)", te: "పెద్దది (115%)" },
  a11ySizeXLarge: { en: "Extra Large (130%)", hi: "अतिरिक्त बड़ा (130%)", te: "మరింత పెద్దది (130%)" },
  a11yContrastTitle: { en: "High Contrast Mode (Outdoor Sunlight)", hi: "हाई कॉन्ट्रास्ट मोड (बाहरी धूप)", te: "హై కాంట్రాస్ట్ మోడ్ (బయటి ఎండ)" },
  a11yContrastDesc: { en: "Maximizes border contrast and background sharpness for outdoor field visits.", hi: "बाहरी फ़ील्ड विज़िट के लिए बॉर्डर कॉन्ट्रास्ट और पृष्ठभूमि स्पष्टता अधिकतम करता है।", te: "బయటి ఫీల్డ్ సందర్శనల కోసం బోర్డర్ కాంట్రాస్ట్ మరియు నేపథ్య స్పష్టతను పెంచుతుంది." },
  a11yMotionTitle: { en: "Reduce Motion & Animations", hi: "एनिमेशन और मोशन कम करें", te: "మోషన్ & యానిమేషన్‌లు తగ్గించండి" },
  a11yMotionDesc: { en: "Disables UI animations and transitions for sensitive users.", hi: "संवेदनशील उपयोगकर्ताओं के लिए UI एनिमेशन और ट्रांज़िशन बंद करता है।", te: "సున్నితమైన వినియోగదారుల కోసం UI యానిమేషన్‌లు మరియు ట్రాన్సిషన్‌లను ఆఫ్ చేస్తుంది." },
  helpGuideSubtitle: { en: "Step-by-step verification flows, rural usability instructions, and technical architecture specs.", hi: "चरण-दर-चरण सत्यापन प्रवाह, ग्रामीण उपयोग निर्देश और तकनीकी आर्किटेक्चर विवरण।", te: "దశలవారీ ధృవీకరణ ప్రవాహాలు, గ్రామీణ వినియోగ సూచనలు మరియు సాంకేతిక ఆర్కిటెక్చర్ వివరాలు." },
  helpGuideWhatTitle: { en: "What is LIFE PATCH?", hi: "LIFE PATCH क्या है?", te: "LIFE PATCH అంటే ఏమిటి?" },
  helpGuideWhatText: { en: "<strong>LIFE PATCH</strong> is a patient-centric, rural-first digital health record platform engineered for <em>Smart India Hackathon 2026 (Problem Statement SIH26133)</em>. It bridges rural citizens, frontline ASHA workers, Primary Health Centres (PHCs), and specialist referral hospitals into an integrated, consent-governed longitudinal health record that functions with 100% offline resilience.", hi: "<strong>LIFE PATCH</strong> एक मरीज़-केंद्रित, ग्रामीण-प्रथम डिजिटल स्वास्थ्य रिकॉर्ड प्लेटफ़ॉर्म है जो <em>स्मार्ट इंडिया हैकथॉन 2026 (समस्या कथन SIH26133)</em> के लिए बनाया गया है। यह ग्रामीण नागरिकों, आशा कार्यकर्ताओं, प्राथमिक स्वास्थ्य केंद्रों (PHC) और विशेषज्ञ रेफरल अस्पतालों को एकीकृत, सहमति-आधारित आजीवन स्वास्थ्य रिकॉर्ड में जोड़ता है जो 100% ऑफ़लाइन भी काम करता है।", te: "<strong>LIFE PATCH</strong> అనేది <em>స్మార్ట్ ఇండియా హ్యాకథాన్ 2026 (ప్రాబ్లమ్ స్టేట్‌మెంట్ SIH26133)</em> కోసం రూపొందించిన రోగి-కేంద్రీకృత, గ్రామీణ-మొదటి డిజిటల్ హెల్త్ రికార్డు ప్లాట్‌ఫారమ్. ఇది గ్రామీణ పౌరులు, ఆశా కార్యకర్తలు, ప్రాథమిక ఆరోగ్య కేంద్రాలు (PHC) మరియు స్పెషలిస్ట్ రిఫరల్ హాస్పిటల్స్‌ను సమ్మతి-ఆధారిత జీవితకాల హెల్త్ రికార్డులోకి కలుపుతుంది — 100% ఆఫ్‌లైన్‌లోనూ పనిచేస్తుంది." },
  helpGuideStepsTitle: { en: "Demonstration Steps for Evaluators & Juries", hi: "मूल्यांकनकर्ताओं और जूरी के लिए प्रदर्शन चरण", te: "మూల్యాంకనకారులు & జ్యూరీ కోసం ప్రదర్శన దశలు" },
  helpGuideStep1: { en: "<strong>Patient Multilingual Voice Entry:</strong> Go to Patient Portal → Report Symptoms → Speak or select a sample phrase in Hindi, Telugu, or English → Save to EHR.", hi: "<strong>मरीज़ की बहुभाषी वॉयस एंट्री:</strong> मरीज़ पोर्टल → लक्षण दर्ज करें → हिंदी, तेलुगु या अंग्रेजी में बोलें या नमूना वाक्य चुनें → EHR में सहेजें।", te: "<strong>రోగి బహుభాషా వాయిస్ ఎంట్రీ:</strong> పేషెంట్ పోర్టల్ → లక్షణాలు నమోదు → తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో మాట్లాడండి లేదా నమూనా వాక్యం ఎంచుకోండి → EHRలో సేవ్ చేయండి." },
  helpGuideStep2: { en: "<strong>Longitudinal Health Timeline:</strong> View the patient's lifetime timeline to see the real-time record addition with verified status.", hi: "<strong>आजीवन स्वास्थ्य टाइमलाइन:</strong> मरीज़ की लाइफ़टाइम टाइमलाइन देखें — नया रिकॉर्ड सत्यापित स्थिति के साथ तुरंत दिखता है।", te: "<strong>జీవితకాల హెల్త్ టైమ్‌లైన్:</strong> రోగి జీవితకాల టైమ్‌లైన్ చూడండి — కొత్త రికార్డు వెంటనే ధృవీకరణ స్థితితో కనిపిస్తుంది." },
  helpGuideStep3: { en: "<strong>Doctor Priority Triage & Queue:</strong> Switch to Doctor Workspace → Check the live OPD priority queue with wait times and override priority.", hi: "<strong>डॉक्टर प्राथमिकता ट्रायज और कतार:</strong> डॉक्टर वर्कस्पेस पर जाएं → प्रतीक्षा समय के साथ लाइव OPD प्राथमिकता कतार देखें और प्राथमिकता बदलें।", te: "<strong>డాక్టర్ ప్రాధాన్యతా ట్రయాజ్ & క్యూ:</strong> డాక్టర్ వర్క్‌స్పేస్‌కు మారండి → వేటింగ్ టైమ్‌లతో లైవ్ OPD ప్రాధాన్యతా క్యూ చూడండి, ప్రాధాన్యత మార్చండి." },
  helpGuideStep4: { en: "<strong>Clinical Review & e-Prescriptions:</strong> Open the patient chart → Review grounded clinical AI summary → Issue an e-prescription with drug allergy checking and print the official slip.", hi: "<strong>क्लिनिकल समीक्षा और ई-पर्चे:</strong> मरीज़ चार्ट खोलें → AI सारांश देखें → दवा-एलर्जी जांच के साथ ई-पर्चा जारी करें और आधिकारिक पर्ची प्रिंट करें।", te: "<strong>క్లినికల్ రివ్యూ & e-ప్రిస్క్రిప్షన్‌లు:</strong> రోగి చార్ట్ తరవండి → AI సారాంశం చూడండి → డ్రగ్ అలర్జీ తనిఖీతో e-ప్రిస్క్రిప్షన్ జారీ చేసి అధికారిక స్లిప్ ప్రింట్ చేయండి." },
  helpGuideStep5: { en: "<strong>District Referral Transfer:</strong> Create a referral to District Hospital Cardiology with encrypted diagnostic sharing.", hi: "<strong>जिला अस्पताल रेफरल:</strong> एन्क्रिप्टेड डायग्नोस्टिक साझाकरण के साथ जिला अस्पताल कार्डियोलॉजी में रेफरल बनाएं।", te: "<strong>జిల్లా ఆసుపత్రి రిఫరల్:</strong> ఎన్‌క్రిప్టెడ్ డయాగ్నోస్టిక్ షేరింగ్‌తో జిల్లా ఆసుపత్రి కార్డియాలజీకి రిఫరల్ సృష్టించండి." },
  helpGuideStep6: { en: "<strong>ASHA Field Visit & Offline Sync:</strong> Switch to ASHA Worker → Record household vitals → Simulate offline storage → Sync to PHC with 1 click.", hi: "<strong>आशा फ़ील्ड विज़िट और ऑफ़लाइन सिंक:</strong> आशा कार्यकर्ता पर जाएं → घरेलू वाइटल्स दर्ज करें → ऑफ़लाइन स्टोरेज देखें → 1 क्लिक में PHC पर सिंक करें।", te: "<strong>ఆశా ఫీల్డ్ విజిట్ & ఆఫ్‌లైన్ సింక్:</strong> ఆశా వర్కర్‌గా మారండి → ఇంటి వద్ద వైటల్స్ నమోదు → ఆఫ్‌లైన్ నిల్వ చూడండి → 1 క్లిక్‌తో PHCకి సింక్ చేయండి." },
  helpGuidePrivacyTitle: { en: "Data Privacy & Architecture Guarantees", hi: "डेटा गोपनीयता और आर्किटेक्चर गारंटी", te: "డేటా గోప్యత & ఆర్కిటెక్చర్ హామీలు" },
  helpGuidePriv1: { en: "<strong>100% Client-Side IndexedDB Engine:</strong> 17 isolated data stores guarantee zero data loss without requiring external cloud databases.", hi: "<strong>100% क्लाइंट-साइड IndexedDB इंजन:</strong> 17 अलग डेटा स्टोर बिना बाहरी क्लाउड डेटाबेस के शून्य डेटा हानि की गारंटी देते हैं।", te: "<strong>100% క్లయింట్-సైడ్ IndexedDB ఇంజిన్:</strong> 17 వేర్వేరు డేటా స్టోర్‌లు బాహ్య క్లౌడ్ డేటాబేస్ లేకుండా డేటా నష్టం శూన్యంగా ఉండేలా హామీ ఇస్తాయి." },
  helpGuidePriv2: { en: "<strong>ABDM-Aligned ABHA Identifiers:</strong> Standardized 14-digit ABHA IDs with consent gatekeeping.", hi: "<strong>ABDM-अनुरूप ABHA पहचान:</strong> सहमति नियंत्रण के साथ मानकीकृत 14-अंकीय ABHA ID।", te: "<strong>ABDM-అనుగుణ ABHA గుర్తింపులు:</strong> సమ్మతి నియంత్రణతో ప్రామాణిక 14-అంకెల ABHA IDలు." },
  helpGuidePriv3: { en: "<strong>Human-in-the-Loop Clinical AI:</strong> AI assists summarization and triage but clinical responsibility remains with licensed doctors.", hi: "<strong>मानव-नियंत्रित क्लिनिकल AI:</strong> AI सारांश और ट्रायज में सहायता करता है, लेकिन क्लिनिकल ज़िम्मेदारी लाइसेंसी डॉक्टर की रहती है।", te: "<strong>మానవ-నియంత్రిత క్లినికల్ AI:</strong> AI సారాంశం & ట్రయాజ్‌లో సహాయపడుతుంది, కానీ క్లినికల్ బాధ్యత లైసెన్స్ పొందిన డాక్టర్‌దే." },
  setSubtitle: { en: "Configure system language, appearance themes, and backup or restore your client-side IndexedDB database.", hi: "सिस्टम भाषा, थीम मोड कॉन्फ़िगर करें और अपने क्लाइंट-साइड IndexedDB डेटाबेस का बैकअप या रिस्टोर करें।", te: "సిస్టమ్ భాష, థీమ్ మోడ్ కాన్ఫిగర్ చేయండి మరియు మీ క్లయింట్-సైడ్ IndexedDB డేటాబేస్‌ను బ్యాకప్ లేదా రీస్టోర్ చేయండి." },
  setPrefsTitle: { en: "User & Language Preferences", hi: "उपयोगकर्ता और भाषा प्राथमिकताएं", te: "వినియోగదారు & భాషా ప్రాధాన్యతలు" },
  setLangLabel: { en: "Display & Speech Language", hi: "डिस्प्ले और वाणी भाषा", te: "ప్రదర్శన & ప్రసంగ భాష" },
  setLangEn: { en: "English (Official Clinical Default)", hi: "अंग्रेजी (आधिकारिक क्लिनिकल डिफ़ॉल्ट)", te: "ఇంగ్లీష్ (అధికారిక క్లినికల్ డిఫాల్ట్)" },
  setLangHi: { en: "हिन्दी (Hindi)", hi: "हिन्दी (Hindi)", te: "हिन्दी (Hindi)" },
  setLangTe: { en: "తెలుగు (Telugu)", hi: "तेलुगु (Telugu)", te: "తెలుగు (Telugu)" },
  setThemeLabel: { en: "Theme Mode", hi: "थीम मोड", te: "థీమ్ మోడ్" },
  setThemeLight: { en: "Light Mode (Medical Standard)", hi: "लाइट मोड (मेडिकल मानक)", te: "లైట్ మోడ్ (మెడికల్ స్టాండర్డ్)" },
  setThemeDark: { en: "Dark Mode (Deep Clinical Navy)", hi: "डार्क मोड (डीप क्लिनिकल नेवी)", te: "డార్క్ మోడ్ (డీప్ క్లినికల్ నేవీ)" },
  setDbTitle: { en: "Local IndexedDB Database Backup & Portability", hi: "लोकल IndexedDB डेटाबेस बैकअप और पोर्टेबिलिटी", te: "లోకల్ IndexedDB డేటాబేస్ బ్యాకప్ & పోర్టబిలిటీ" },
  setDbBadge: { en: "17 Stores Active", hi: "17 स्टोर सक्रिय", te: "17 స్టోర్‌లు యాక్టివ్" },
  setDbDesc: { en: "Because LIFE PATCH operates as a 100% zero-server offline-capable system, all clinical transactions (patients, vitals, prescriptions, triage queue, AI summaries) reside in your browser's local IndexedDB. You can export complete snapshots to JSON or restore existing records.", hi: "चूंकि LIFE PATCH 100% सर्वर-रहित ऑफ़लाइन सिस्टम है, सभी क्लिनिकल रिकॉर्ड (मरीज़, वाइटल्स, पर्चे, ट्रायज कतार, AI सारांश) आपके ब्राउज़र के लोकल IndexedDB में रहते हैं। आप JSON में पूरा बैकअप निर्यात कर सकते हैं या मौजूदा रिकॉर्ड रिस्टोर कर सकते हैं।", te: "LIFE PATCH 100% సర్వర్-లేని ఆఫ్‌లైన్ సిస్టమ్ అయినందున, అన్ని క్లినికల్ రికార్డులు (పేషెంట్లు, వైటల్స్, ప్రిస్క్రిప్షన్లు, ట్రయాజ్ క్యూ, AI సారాంశాలు) మీ బ్రౌజర్ లోకల్ IndexedDBలో ఉంటాయి. మీరు పూర్తి బ్యాకప్‌ను JSONగా ఎగుమతి చేయవచ్చు లేదా రికార్డులను రీస్టోర్ చేయవచ్చు." },
  setResetTitle: { en: "Re-seed Demo Database", hi: "डेमो डेटाबेस री-सीड करें", te: "డెమో డేటాబేస్ రీ-సీడ్ చేయండి" },
  setResetDesc: { en: "Resets all IndexedDB stores to the original SIH synthetic demonstration dataset.", hi: "सभी IndexedDB स्टोर को मूल SIH सिंथेटिक प्रदर्शन डेटासेट पर रीसेट करता है।", te: "అన్ని IndexedDB స్టోర్‌లను అసలు SIH సింథటిక్ డెమో డేటాసెట్‌కు రీసెట్ చేస్తుంది." },
  setResetBtn: { en: "Reset to Clean Seed", hi: "क्लीन सीड पर रीसेट करें", te: "క్లీన్ సీడ్‌కు రీసెట్" },

  // ─── Dynamic / Sentinel ─────────────────────────
  timeGreeting: { en: "Good morning", hi: "सुप्रभात", te: "శుభోదయం" },
};
