/**
 * LIFE PATCH - Deterministic Clinical AI Assistant (Demo Mode)
 * Grounded in live patient records, vitals, symptoms, and labs.
 * Strictly adheres to "AI-assisted — Human clinical decision required".
 */

export function generateClinicalSummary(patient, vitals = [], symptoms = [], records = [], prescriptions = []) {
  const latestVital = vitals[0] || null;
  const recentSymptoms = symptoms.filter(s => s.status !== 'Resolved');
  const activeConditions = patient.chronicConditions || [];
  
  const alerts = [];
  const reviewPoints = [];

  // Check BP
  if (latestVital && (latestVital.bpSystolic >= 140 || latestVital.bpDiastolic >= 90)) {
    alerts.push(`Elevated Blood Pressure recorded (${latestVital.bpSystolic}/${latestVital.bpDiastolic} mmHg on ${latestVital.recordedAt.split('T')[0]}).`);
    reviewPoints.push('Evaluate anti-hypertensive regimen adherence and dosage adjustment.');
  }

  // Check Blood Sugar
  if (latestVital && latestVital.bloodSugarRandom && latestVital.bloodSugarRandom > 160) {
    alerts.push(`Random blood glucose elevated (${latestVital.bloodSugarRandom} mg/dL).`);
    reviewPoints.push('Check glycemic control & recent dietary habits; assess HbA1c necessity.');
  }

  // Check Active Symptoms
  if (recentSymptoms.length > 0) {
    const symList = recentSymptoms.map(s => `"${s.symptomName}" (Severity: ${s.severity})`).join(', ');
    reviewPoints.push(`Recent unreviewed symptoms: ${symList}.`);
  }

  // Check Allergies
  if (patient.allergies && patient.allergies.length > 0 && !patient.allergies.includes('None known')) {
    alerts.push(`Known Patient Allergies: ${patient.allergies.join(', ')}.`);
  }

  return {
    patientOverview: `${patient.name}, ${patient.age} yrs (${patient.gender}). Known history of ${activeConditions.join(', ') || 'No chronic conditions'}.`,
    clinicalAlerts: alerts.length > 0 ? alerts : ['No acute vital threshold alerts detected.'],
    suggestedReviewAreas: reviewPoints.length > 0 ? reviewPoints : ['Routine health maintenance & lifestyle counselling.'],
    activePrescriptionsCount: prescriptions.length,
    disclaimer: 'Generated by LIFE PATCH Clinical AI Assistant (Local Demo). This summary supports documentation and triage; final clinical decisions and prescriptions must be made solely by the consulting physician.'
  };
}
